sec2/apps/afiliados/urls.py
# Importaciones del sistema
from django.urls import path
# Importaciones locales
from selectable import urls as selectable_urls
from .views import *
from django.contrib.auth.decorators import login_required, permission_required



app_name = "afiliados"

urlpatterns = [
    path('',index, name="index"),

    #AFILIADO
    path('afiliados/afiliado/crear/',AfiliadoCreateView.as_view(), name="afiliado_crear"),
    path('afiliados/afiliado/<int:pk>',AfiliadoDetailView.as_view(), name="afiliado_detalle"),
    path('afiliados/afiliado/<int:pk>/editar', AfiliadoUpdateView.as_view(), name="afiliado_actualizar"),
    path('afiliados/listar',AfiliadosListView.as_view(), name="afiliado_listar"),
    path('afiliados/afiliado/<int:pk>/<str:accion>/<str:origen>/', afiliado_afiliar_desafiliar, name="afiliado_afiliar_desafiliar"),
    #ALTA GRUPO FAMILIAR (accedido desde afiliado)
    path('afiliado/<int:pk>/grupoFamiliar/crear', FamiliaCreateView.as_view(), name="crear_familiar"),

    #RELACION AFILIADO-GRUPO FAMILIAR
    path('grupofamiliar/listado', RelacionFamiliarListView.as_view(), name="grupo_familiar_listar"),

    #GRUPO FAMILIAR
    path('grupofamiliar/crear', alta_familiar, name="crear_familiar_directo"),
    path('afiliado/<int:pk>/grupoFamiliar/familia/<int:familiar_pk>', FamiliarDetailView.as_view(), name="familiar_detalle"),
    path('afiliado/<int:pk>/grupoFamiliar/familia/<int:familiar_pk>/editar/', FamiliarUpdateView.as_view(), name="familiar_editar"),
    path('afiliado/<int:pk>/grupoFamiliar/familia/<int:familiar_pk>/eliminar', familiar_eliminar, name="familiar_eliminar"),

    # path('afiliado/grupoFamiliar/familia/<int:familiar_pk>/editar', FamiliarUpdateView_.as_view(), name="familiar_editar_"),
    #ACCEDIDOS DESDE LA APLICACION DE CURSOS
    # path('afiliado/grupoFamiliar/familia/<int:familiar_pk>', FamiliarDetailVentanaNuevaView_.as_view(), name="familiar_detalle_"),

    #GENERAR PDF
    path('pago/afiliado/afiliado/<int:pk>/generarnota', confeccionarNota ,name="confeccionar_nota"),
    path('pago/afiliado/cuotas', PagoCuotaCreateView.as_view() ,name="pagar_cuota_sindical"),
    
    path('pago/listado', PagoCuotaListView.as_view() ,name="pago_cuota_listado"),
    path('pago/ruta_para_actualizar_afiliados/', obtener_afiliados_por_cuit_empleador, name='ruta_para_actualizar_afiliados'),
    
    path('pago/afiliado/actualizar', cuota_sindical_actualizar_estado ,name="actualizar_estado"),
 
]

sec2/apps/alquileres/urls.py
from django.urls import path
from .views import *
from . import views

app_name="alquiler"


urlpatterns = [
    path('',index, name="index"),
    
    # ENCARGADO
    path('encargados/listado',EncargadoListView.as_view(), name="encargado_listar"),
    path('encargados/encargado/crear/',EncargadoCreateView.as_view(), name="encargado_alta"),
    path('encargados/encargado/<int:pk>', EncargadoDetailView.as_view(), name="encargado_detalle"),
    path('encargados/encargado/<int:pk>/editar', EncargadoUpdateView.as_view(), name="encargado_editar"),

    # SERVICIO
    path('servicios/', GestionServicioView.as_view(), name="gestion_servicio"),
    path('servicio/servicio/<int:pk>/', ServicioDetailView.as_view(), name='servicio_detalle'),
    path('aulas/aula/<int:pk>/editar', ServicioUpdateView.as_view(), name="servicio_editar"),
    path('aulas/aula/<int:pk>/eliminar', servicio_eliminar, name="servicio_eliminar"),

    # SALON
    path('salones',SalonesListView.as_view(), name="salon_listar"),
    path('salones/salon/crear/',SalonCreateView.as_view(), name="salon_crear"),
    path('salones/salon/<int:pk>',SalonDetailView.as_view(), name="salon_detalle"),
    path('salones/salon/<int:pk>/editar', SalonUpdateView.as_view(), name="salon_actualizar"),
    path('salones/salon/<int:pk>/eliminar', salon_eliminar, name="salon_eliminar"),

    # ALQUILER
    path('alquileres/',AlquilieresListView.as_view(), name="alquiler_listar"),
    path('alquileres/alquiler/crear',AlquilerCreateView.as_view(), name="alquiler_crear"),
    path('alquileres/alquiler/<int:pk>',AlquilerDetailView.as_view(), name="alquiler_detalle"),
    # path('modificar/<int:pk>', AlquilerUpdateView.as_view(), name="alquiler_actualizar"),
    path('alquileres/alquiler/<int:pk>/agregarlistaespera',agregar_lista_espera, name="agregar_lista_espera"),
    path('alquileres/alquiler/<int:pk>/reemplazarinquilino', reemplazar_inquilino, name="reemplazar_inquilino"),
    path('alquileres/alquiler/<int:alquiler_pk>/listaespera/quitar/<int:afiliado_pk>', quitar_lista_alquiler, name="quitar_lista_alquiler"),

    path('alquileres/alquiler/<int:pk>/eliminar', alquiler_eliminar, name="alquiler_eliminar"),
    
    # PAGO DE ALQUILER
    path('crearPago/',PagoAlquilerCreateView.as_view(), name="pagar_alquiler_crear"),

]

sec2/apps/cursos/urls.py
from django.urls import path
from .views.actividad_views import *
from .views.curso_views import *
from .views.dictado_views import *
from .views.horario_views import *
from .views.clase_views import *
from .views.profesor_views import *
from .views.alumno_views import *
from .views.aula_views import *
from .views.pago_views import *
from .views.views import *

app_name="cursos"

urlpatterns = [
    # PRINCIPAL
    path('',index, name="index"),

    # ACTIVIDADES
    path('actividades/', GestionActividadView.as_view(), name="gestion_actividad"),
    path('actividades/actividad/<int:pk>', ActividadDetailView.as_view(), name="actividad_detalle"),
    path('actividades/actividad/<int:pk>/editar', ActividadUpdateView.as_view(), name="actividad_editar"),
    path('actividades/actividad/<int:pk>/eliminar', actividad_eliminar, name="actividad_eliminar"),

    # AULAS
    path('aulas/', GestionAulaView.as_view(), name="gestion_aula"),
    path('aulas/aula/<int:pk>/', AulaDetailView.as_view(), name='aula_detalle'),
    path('aulas/aula/<int:pk>/editar', AulaUpdateView.as_view(), name="aula_editar"),
    path('aulas/<int:pk>/eliminar', aula_eliminar, name="aula_eliminar"),

    # PROFESOR
    path('profesores', ProfesorListView.as_view(), name="profesor_listado"),
    path('profesores/profesor/crear', ProfesorCreateView.as_view(), name="profesor_crear"),
    path('profesores/profesor/<int:pk>', ProfesorDetailView.as_view(), name="profesor_detalle"),
    path('profesores/profesor/<int:pk>/editar', ProfesorUpdateView.as_view(), name="profesor_editar"),
    path('profesores/profesor/<int:pk>/eliminar', profesor_eliminar, name="profesor_eliminar"),

    # CURSOS
    path('cursos/listado', CursoListView.as_view(), name="curso_listado"),
    path('cursos/curso/crear/', CursoCreateView.as_view(), name="curso_crear"),
    path('cursos/curso/<int:pk>', CursoDetailView.as_view(), name="curso_detalle"),
    path('cursos/curso/<int:pk>/editar', CursoUpdateView.as_view(), name="curso_editar"),
    path('cursos/curso/<int:pk>/eliminar', curso_eliminar, name="curso_eliminar"),
    path('cursos/curso/<int:pk>/listaespera', cursoListaEspera, name="curso_lista_espera"),
    path('cursos/curso/<int:pk>/listaespera/rol/<int:rol_pk>/<str:accion>/', gestionListaEspera, name="gestion_lista_espera"),
    
    # GESTION DE LISTA DE ESPERA
    path('cursos/curso/<int:pk>/listaespera/alumnopotencial/inscribir', AlumnoPotencialCreateView.as_view(), name="alumno_nuevo_lista_espera"),

    ## VERIFICAR Y BUSCAR PERSONA ANTES DE PROCEDER A LA INSCRIPCION
    path('cursos/curso/<int:curso_pk>/verificarpersona', VerificarInscripcionView.as_view(), name="verificar_persona"),
    path('buscar-persona/', BuscarPersonaView.as_view(), name='buscar_persona'),

    # DICTADOS (accedido desde cursos)
    path('cursos/curso/<int:pk>/dictados/dictado/crear', DictadoCreateView.as_view(), name="dictado_crear"),
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>', DictadoDetailView.as_view(), name="dictado_detalle"),
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/editar', DictadoUpdateView.as_view(), name="dictado_editar"),
    
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/finalizar', finalizarDictado , name="dictado_finalizar"),

    # HORARIO (accedido desde dictado)
    path('curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/horarios/horario/crear/', HorarioCreateView.as_view(), name='horario_crear'),
    path('curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/horarios/horario/<int:horario_pk>/elminar', eliminarHorario, name='horario_eliminar'),

    # ASIGNACIÓN DE AULA (accedido desde el horario)
    path('curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/horarios/horario/<int:horario_id>/vincularAula/', asignar_aula, name='asignar_aula'),

    # CLASE (accedido desde dictaod)
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_id>/generarclaeses/', generar_clases, name="generar_clases"),
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/clases/clase/<int:clase_pk>', ClaseDetailView.as_view(), name="clase_detalle"),
    
    # ALUMNO (accedido desde el dictado)

    #CONTROL DE ASISTENCIA
    path('marcar_asistencia/Alumno/<int:clase_id>/', marcar_asistencia, name='generar_asistencia'),

    #ALUMNNOS POR CURSO
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/Alumnos', AlumnosEnDictadoList.as_view(), name="alumno_inscripto"),

    # GESTION DE INSCRIPCION
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/<str:tipo>/<int:persona_pk>/Incripcion/<str:accion>/', gestionInscripcion, name="gestion_inscripcion"),
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/AlumnoNuevo/inscribir', AlumnoCreateView.as_view(), name="alumno_nuevo_inscribir"),

    path('alumnos', AlumnosListView.as_view(), name="alumnos_listado"),
    path('alumnos/alumnno/<int:pk>/', AlumnoDetailView.as_view(), name="alumno_detalle"),
    path('alumnos/alumno/<int:pk>/eliminar', alumno_eliminar, name="alumno_eliminar"),

    #GENERAR PDF
    path('generar-pdf-afiliado-dictado/<int:dictado_pk>/<int:persona_pk>', generarPDF_Afiliado , name="generar_pdf_dictado_finalizado_afiliado"),
    
    #NO SE UTILIZARIA
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/Alumnos/listaEspera', listaEspera , name="dictado_lista_espera"),
    path('pago/listado/profesor', PagoProfesorListView.as_view() ,name="pago_cuota_profesor_listado"),
    path('pago/profesor/crear', PagoProfesorCreateView.as_view(), name="pago_profesor"),
    path('pago/profesor/<int:pk>', PagoProfesorDetailView.as_view(), name="pago_profesor_detalle"),
    path('get_dictados_por_titular/<int:titular_pk>/', get_dictados_por_titular, name='get_dictados_por_titular'),

    path('pago/listado/alumno', PagoAlumnoListView.as_view() ,name="pago_cuota_alumno_listado"),
    path('pago/obtenerDictadosEnCurso/<int:pk>', obtenerDictadosEnCurso ,name="obtenerDictadoEnCurso"),

    path('pago/alumno/crear', PagoAlumnoCreateView.as_view(), name="pago_alumno_crear"),
    path('pago/alumno/<int:pk>', PagoAlumnoDetailView.as_view(), name="pago_alumno_detalle"),

    path('get_dictados_por_alumno/<int:rol_pk>/', get_dictados_por_alumno, name='get_dictados_por_alumno'),
]

sec2/sec2/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


handler403 = custom_403_view
urlpatterns = [
    
    #PRINCIPALES
    
    path('', home, name="login"),
    path('admin/', admin.site.urls),
    path('home/', home, name="home"),

    #APLICACIONES
    path('home/app_afiliados/',include('apps.afiliados.urls')),
    path('home/app_cursos/',include('apps.cursos.urls')),
    path('home/app_personas/',include('apps.personas.urls')),
    path('home/app_alquileres/',include('apps.alquileres.urls')),
    path('home/app_reportes/',include('apps.reportes.urls')),

    path('',include('apps.users.urls')),
    path('select2/', include('django_select2.urls')),
    path('selectable/', include('selectable.urls')),

    path('manual_usuario/', abrirManualUsuario, name="manual_usuario"),
    path('documentacion_tecnica/', abrirDocumentacionTecnica, name="documentacion_tecnica"),


]

sec2/apps/afiliados/models.py
from django.db import models
from apps.cursos.models import Dictado
from apps.personas.models import Rol
from utils.choices import AFILIADO_ESTADO, LOCALIDADES_CHUBUT, TIPOS_RELACION_FAMILIAR
from utils.constants import *
from utils.funciones import validate_no_mayor_actual
from utils.regularexpressions import *
from datetime import date
from django.utils import timezone

# -------------------- FAMILIAR ------------------
class Familiar(Rol):
    TIPO = ROL_TIPO_FAMILIAR  # Define un valor único para el tipo de rol de Familiar
    activo = models.BooleanField(default=False)  # Agregamos el campo "activo" con valor predeterminado True
    dictados = models.ManyToManyField(Dictado, related_name="familiares", blank=True)
    # lista_espera = models.ManyToManyField(Dictado, related_name='familiares_en_espera', blank=True)
    
    def __str__(self):
        return f"Activo: {self.activo}"

Rol.register(Familiar)

# -------------------- AFILIADO ------------------
class Afiliado(Rol):
    class Meta:
        permissions = [("permission_gestion_afiliado", "Control total afiliado")]

    #Utilizado para Rol
    TIPO = ROL_TIPO_AFILIADO
    estado = models.PositiveSmallIntegerField(choices=AFILIADO_ESTADO, default=1)
    razon_social = models.CharField(max_length=50, validators=[text_and_numeric_validator])
    categoria_laboral = models.CharField(max_length=50, validators=[text_and_numeric_validator])
    rama = models.CharField(max_length=50, validators=[text_and_numeric_validator])
    sueldo = models.IntegerField(validators=[MinValueValidator(0, 'El sueldo debe ser un valor positivo.')])
    horaJornada = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    cuit_empleador = models.CharField(max_length=11, validators=[numeric_validator], help_text='Cuit sin puntos y guiones. Ej: 01234567899')
    domicilio_empresa = models.CharField(max_length=100, validators=[text_and_numeric_validator], help_text='Calle y numero')

    fechaAfiliacion= models.DateField(
        null=True,
        blank=False,
        validators=[validate_no_mayor_actual]
    )
    fechaIngresoTrabajo = models.DateField(
        null=False,
        blank=False,
        validators=[validate_no_mayor_actual]
    )
    localidad_empresa = models.CharField(
        max_length=30,
        choices=LOCALIDADES_CHUBUT,
        default="TRELEW",
    )

    dictados = models.ManyToManyField(Dictado, related_name="afiliados", blank=True)
    # lista_espera = models.ManyToManyField(Dictado, related_name='afiliados_en_espera', blank=True)
    familia = models.ManyToManyField(Familiar, through='RelacionFamiliar', blank=True)
    
    def __str__(self):
        return f"{self.persona.dni} {self.persona.apellido} {self.persona.nombre}. Estado: {self.get_estado_display()}"
    
    def __strextra__(self):
        # Define your new string representation here
        return f"{self.persona.dni} | {self.persona}"
    
    def tiene_esposo(self):
        esposo_existente = self.familia.filter(relacionfamiliar__tipo_relacion=1).exists()
        return esposo_existente
    
    """una vez activado al afiliado pondra a los familiares en estado de activo"""
    def activar_familiares(self):
        familiares = self.familia.all()
        for familiar in familiares:
            familiar.activo = True
            familiar.save()
    
    def dar_de_baja_familiares(self):
        familiares = self.familia.all()
        for familiar in familiares:
            familiar.activo = False
            familiar.hasta = timezone.now()
            familiar.save()

    def valorCuota(self):
        # Calcular el 1% del sueldo
        return self.sueldo * 0.01
    
    def actualizarSueldo(self, monto):
        self.sueldo = monto * 100
        self.save()

    def afiliar(self):
        self.fechaAfiliacion = date.today()
        # self.desde = fechaAfiliacion
        self.estado = 2
        self.persona.es_afiliado = True
        self.activar_familiares()
        self.persona.save()
        self.save()

    def desafiliar(self):
        self.hasta = date.today()
        self.estado = 3
        self.persona.es_afiliado = False
        self.dar_de_baja_familiares()
        self.persona.save()
        self.save()

Rol.register(Afiliado)

# -------------------- RELACION FAMILIAR-AFILIADO ------------------
class RelacionFamiliar(models.Model):
    afiliado = models.ForeignKey(Afiliado, on_delete=models.CASCADE)
    familiar = models.ForeignKey(Familiar, on_delete=models.CASCADE)
    tipo_relacion = models.PositiveSmallIntegerField(choices=TIPOS_RELACION_FAMILIAR)

    def __str__(self):
        return f"Relación: {self.get_tipo_relacion_display()}"

# -------------------- PAGO DE CUOTA ------------------
class PagoCuota(models.Model):
    afiliado = models.ForeignKey(Afiliado, on_delete=models.CASCADE, related_name='pagos_cuotas')
    monto = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0, 'El monto debe ser un valor positivo.')])
    pdf_transferencia = models.FileField(upload_to='transferencias/', null=True, blank=True)
    fecha_pago = models.DateField(default=timezone.now)

sec2/apps/afiliados/templates/afiliados/afiliado_detalle.html
{% extends 'detalle_listado_afiliado.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block detalle %}
<link href="{% static 'css/afiliado_confirm_delete.css' %}" rel="stylesheet" />

<h3>{{subtitulodetalle1}}</h3>
{% include "persona_detalle.html" with persona=afiliado.persona %}
<h3>{{subtitulodetalle2}}</h3>
{% include "afiliados/afiliado_mostrar_datos.html" %}
{% endblock %}


{% block botones %}
<div class="col"> 
  <a href="{% url 'afiliados:afiliado_listar' %}" class="btn btn-sm btn-secondary btn-detalle">
    <i class="fa-solid fa-arrow-left"></i> Ir al listado
  </a>
</div>

{% if afiliado.estado == 1 or afiliado.estado == 2 %}
<div class="col text-center"> 
    <a href="{% url 'afiliados:afiliado_actualizar' afiliado.pk %}" class="btn btn-sm btn-detalle btn-primary ">
      <i class="fa-regular fa-pen-to-square"></i>
       Modificar</a>
</div>
{% endif %}

<div class="col text-center"> 
  <a href="{% url 'afiliados:confeccionar_nota' afiliado.pk %}" class="btn btn-sm btn-light btn-detalle">
    <i class="fa-solid fa-file-pdf"></i>PDF</a>
</div>

<div class="col text-center">
  <button type="button" class="btn btn-info btn-sm btn-detalle" data-bs-toggle="modal" data-bs-target="#modalGrupoFamiliar">
    <i class="fas fa-users"></i>
    Grupo Familiar
  </button>
  {% include "afiliados/modal_afiliado_mostrar_grupoFamiliar.html" with relacion_familiar_list=relacion_familiar_list%}
</div>

<div class="col text-center">
  <button type="button" class="btn btn-warning btn-sm btn-detalle" data-bs-toggle="modal" data-bs-target="#modalCuotas  ">
  <i class="fa-solid fa-credit-card"></i>
  Cuotas
</button>
{% include "afiliados/modal_estado_cuotas.html" with cuotas=cuotas%}
</div>

<div class="col text-center">
  <button type="button" class="btn btn-warning btn-sm btn-detalle" data-bs-toggle="modal" data-bs-target="#modalPagos">
    <i class="fa-solid fa-sack-dollar"></i>
    Pagos
  </button>
  {% include "afiliados/modal_estado_pagos.html" with pagos=pagos%}
  </div>

<div class="col text-end">
  {% if afiliado.estado == 1 %}
  <button type="button" class="btn btn-success btn-sm btn-detalle" data-bs-toggle="modal" data-bs-target="#modal_afiliar_{{ afiliado.pk }}">
    <i class="fa-regular fa-circle-down"></i> Aceptar
  </button>
  {% include 'modal_confirm_alta.html' with object=afiliado detalleAfiliadoParam='detalleAfiliado' %}
  {% endif %}
  
  {% if afiliado.estado == 2 %}
  <button type="button" class="btn btn-danger btn-sm btn-detalle" data-bs-toggle="modal" data-bs-target="#modal_desafiliar_{{ afiliado.pk }}"><i class="fa-regular fa-circle-down"></i> Desafiliar</button>
  {% include 'modal_confirm_baja.html' with object=afiliado detalleAfiliadoParam='detalleAfiliado' %}
  {% endif %}
</div>

{% endblock %}

{% block listado_asociado %}
{% if afiliado.dictados.all %}
  <div class="container-sm">
    <h3 class="subtitulo">{{ tituloListado1 }}</h3>
    {% include "inscripcion_dictado.html" with dictados=afiliado.dictados.all %}
  </div>
{% endif %}

{% if alquileres %}
<div class="container-sm">
  <h3 class="subtitulo">{{ tituloListado2 }}</h3>
  {% include "afiliados/afiliado_alquiler.html" with alquileres=alquileres.all %}
</div>
{% endif %}

{% if alquileres %}
<div class="container-sm">
  <h3 class="subtitulo">{{ tituloListado3 }}</h3>
  {% include "afiliados/afiliado_alquiler.html" with alquileres=alquileres_lista_espera.all %}
</div>
{% endif %}


{% endblock %}

sec2/apps/afiliados/templates/afiliados/afiliado_list.html
{% extends 'listado_afiliado.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block botones %}
  <a href="{% url 'afiliados:afiliado_crear' %}" class="btn btn-outline-success btn-sm btn-detalle"><i class="fa-solid fa-plus"></i> Nuevo</a>
{% endblock %}

{% block tabla_listado %}
<table class="table table-sm table-hover">
  <thead>
      <tr>
        <th>#</th>
        {% include 'tabla_persona_cabecera.html' %}
        <th class="text-center">Estado</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for afiliado in page_obj %}
        <tr>
          <td class="negrita"> {{ page_obj.start_index|add:forloop.counter0 }}</td>
          {% include 'tabla_persona_cuerpo.html' with persona=afiliado.persona %}
          <td class="text-center">
            {% if afiliado.estado == 1 %}<i class="fa-solid fa-circle-exclamation" style="color: #FF8000;"></i>{% endif %}
            {% if afiliado.estado == 2 %}<i class="fa-regular fa-circle-check" style="color: #008f00;"></i>{% endif %}
            {% if afiliado.estado == 3 %}<i class="fa-solid fa-circle-minus" style="color: #a80000;"></i>{% endif %}
            {% if afiliado.estado == 5 %}<i class="fa-solid fa-ban"></i>{% endif %}
          </td>

          <td class="text-end">
            {% if afiliado.estado == 1 %}
              <button type="button" class="btn btn-success btn-sm btn-detalle" data-bs-toggle="modal" data-bs-target="#modal_afiliar_{{ afiliado.pk }}"><i class="fa-regular fa-circle-down"></i> Aceptar</button>
              {% include 'modal_confirm_alta.html' with object=afiliado detalleAfiliadoParam='listadoAfiliado' %}
              {% elif afiliado.estado == 2 %}
              <button type="button" class="btn btn-danger btn-sm btn-detalle" data-bs-toggle="modal" data-bs-target="#modal_desafiliar_{{ afiliado.pk }}"><i class="fa-regular fa-circle-down"></i> Desafiliar</button>
              {% include 'modal_confirm_baja.html' with object=afiliado detalleAfiliadoParam='listadoAfiliado'%}
            {% endif %}
            <a href="{% url 'afiliados:afiliado_detalle' afiliado.pk %}" class="btn btn-info btn-sm btn-detalle"><i class="fa-regular fa-eye"></i> Detalle</a>            
          </td>
        </tr>
      {% endfor %}
    </tbody>
</table>
{% endblock %}

sec2/apps/afiliados/templates/afiliados/buscar_afiliado.html
{% extends 'alta_gestion_afiliados.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block formulario %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"></button>
</form>

{% endblock %}

{% block extrajs_intermedia_00 %}
{% endblock %}

sec2/apps/afiliados/templates/afiliados/modal_afiliado_mostrar_grupoFamiliar.html
<!-- Modal -->
<div class="modal fade" id="modalGrupoFamiliar" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title fs-5" id="exampleModalLabel">Grupo Familiar</h2>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          {% if relacion_familiar_list %}
          <table class="table table-sm table-hover">
            <thead>
              <tr>
                <th>#</th>
                <th>Dni</th>
                <th>Vinculo</th>
                <th>Apellido</th> 
                <th>Nombre</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              
              {% for relacion_familiar in relacion_familiar_list %}
              <tr>
                  <td class="negrita">{{ forloop.counter }}</td>
                  <td>{{ relacion_familiar.familiar.persona.dni }}</td>
                  <td>{{ relacion_familiar.get_tipo_relacion_display }}</td>
                  <td>{{ relacion_familiar.familiar.persona.apellido }}</td>
                  <td>{{ relacion_familiar.familiar.persona.nombre }}</td>
                  <td class="text-end">
                      <a href="{% url 'afiliados:familiar_detalle' pk=afiliado.pk familiar_pk=relacion_familiar.familiar.pk %}" class="btn btn-info btn-detalle btn-sm">
                          <i class="fa-regular fa-eye"></i> Detalle
                      </a>
                  </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          {% else %}
          <p>No familiar asociado al afiliado.</p>
          {% endif %}
        </div>
        <div class="modal-footer">
            {% if afiliado.estado == 1 or afiliado.estado == 2 %}
            <a href="{% url 'afiliados:crear_familiar' afiliado.pk %}" 
                class="btn btn-outline-success btn-sm">
                <i class="fa-solid fa-plus"></i> Nuevo Familiar
            {% endif %}
          </a>
        </div>
      </div>
    </div>
  </div>
  