sec2/apps/afiliados/urls.py
# Importaciones del sistema
from django.urls import path
# Importaciones locales
from selectable import urls as selectable_urls
from .views import *
from django.contrib.auth.decorators import login_required, permission_required



app_name = "afiliados"

urlpatterns = [
    path('',index, name="index"),

    #AFILIADO
    path('afiliados/afiliado/crear/',AfiliadoCreateView.as_view(), name="afiliado_crear"),
    path('afiliados/afiliado/<int:pk>',AfiliadoDetailView.as_view(), name="afiliado_detalle"),
    path('afiliados/afiliado/<int:pk>/editar', AfiliadoUpdateView.as_view(), name="afiliado_actualizar"),
    path('afiliados/listar',AfiliadosListView.as_view(), name="afiliado_listar"),
    path('afiliados/afiliado/<int:pk>/<str:accion>/<str:origen>/', afiliado_afiliar_desafiliar, name="afiliado_afiliar_desafiliar"),
    #ALTA GRUPO FAMILIAR (accedido desde afiliado)
    path('afiliado/<int:pk>/grupoFamiliar/crear', FamiliaCreateView.as_view(), name="crear_familiar"),

    #RELACION AFILIADO-GRUPO FAMILIAR
    path('grupofamiliar/listado', RelacionFamiliarListView.as_view(), name="grupo_familiar_listar"),

    #GRUPO FAMILIAR
    path('grupofamiliar/crear', alta_familiar, name="crear_familiar_directo"),
    path('afiliado/<int:pk>/grupoFamiliar/familia/<int:familiar_pk>', FamiliarDetailView.as_view(), name="familiar_detalle"),
    path('afiliado/<int:pk>/grupoFamiliar/familia/<int:familiar_pk>/editar/', FamiliarUpdateView.as_view(), name="familiar_editar"),
    path('afiliado/<int:pk>/grupoFamiliar/familia/<int:familiar_pk>/eliminar', familiar_eliminar, name="familiar_eliminar"),

    # path('afiliado/grupoFamiliar/familia/<int:familiar_pk>/editar', FamiliarUpdateView_.as_view(), name="familiar_editar_"),
    #ACCEDIDOS DESDE LA APLICACION DE CURSOS
    # path('afiliado/grupoFamiliar/familia/<int:familiar_pk>', FamiliarDetailVentanaNuevaView_.as_view(), name="familiar_detalle_"),

    #GENERAR PDF
    path('pago/afiliado/afiliado/<int:pk>/generarnota', confeccionarNota ,name="confeccionar_nota"),
    path('pago/afiliado/cuotas', PagoCuotaCreateView.as_view() ,name="pagar_cuota_sindical"),
    
    path('pago/listado', PagoCuotaListView.as_view() ,name="pago_cuota_listado"),
    path('pago/ruta_para_actualizar_afiliados/', obtener_afiliados_por_cuit_empleador, name='ruta_para_actualizar_afiliados'),
    
    path('pago/afiliado/actualizar', cuota_sindical_actualizar_estado ,name="actualizar_estado"),
 
]

sec2/apps/alquileres/urls.py
from django.urls import path
from .views import *
from . import views

app_name="alquiler"


urlpatterns = [
    path('',index, name="index"),
    
    # ENCARGADO
    path('encargados/listado',EncargadoListView.as_view(), name="encargado_listar"),
    path('encargados/encargado/crear/',EncargadoCreateView.as_view(), name="encargado_alta"),
    path('encargados/encargado/<int:pk>', EncargadoDetailView.as_view(), name="encargado_detalle"),
    path('encargados/encargado/<int:pk>/editar', EncargadoUpdateView.as_view(), name="encargado_editar"),

    # SERVICIO
    path('servicios/', GestionServicioView.as_view(), name="gestion_servicio"),
    path('servicio/servicio/<int:pk>/', ServicioDetailView.as_view(), name='servicio_detalle'),
    path('aulas/aula/<int:pk>/editar', ServicioUpdateView.as_view(), name="servicio_editar"),
    path('aulas/aula/<int:pk>/eliminar', servicio_eliminar, name="servicio_eliminar"),

    # SALON
    path('salones',SalonesListView.as_view(), name="salon_listar"),
    path('salones/salon/crear/',SalonCreateView.as_view(), name="salon_crear"),
    path('salones/salon/<int:pk>',SalonDetailView.as_view(), name="salon_detalle"),
    path('salones/salon/<int:pk>/editar', SalonUpdateView.as_view(), name="salon_actualizar"),
    path('salones/salon/<int:pk>/eliminar', salon_eliminar, name="salon_eliminar"),

    # ALQUILER
    path('alquileres/',AlquilieresListView.as_view(), name="alquiler_listar"),
    path('alquileres/alquiler/crear',AlquilerCreateView.as_view(), name="alquiler_crear"),
    path('alquileres/alquiler/<int:pk>',AlquilerDetailView.as_view(), name="alquiler_detalle"),
    # path('modificar/<int:pk>', AlquilerUpdateView.as_view(), name="alquiler_actualizar"),
    path('alquileres/alquiler/<int:pk>/agregarlistaespera',agregar_lista_espera, name="agregar_lista_espera"),
    path('alquileres/alquiler/<int:pk>/reemplazarinquilino', reemplazar_inquilino, name="reemplazar_inquilino"),
    path('alquileres/alquiler/<int:alquiler_pk>/listaespera/quitar/<int:afiliado_pk>', quitar_lista_alquiler, name="quitar_lista_alquiler"),

    path('alquileres/alquiler/<int:pk>/eliminar', alquiler_eliminar, name="alquiler_eliminar"),
    
    # PAGO DE ALQUILER
    path('crearPago/',PagoAlquilerCreateView.as_view(), name="pagar_alquiler_crear"),

]

sec2/apps/reportes/urls.py
from django.urls import path

from apps.reportes.views import *

app_name="reportes"


urlpatterns = [
    path('reportes/alquileres_por_mes',reportesView.as_view(), name="alquileres_por_mes"),
    path('reportes/afiliados_historico',AfiliadosReportesView.as_view(), name="afiliados_historico"),
    path('reportes/cursos_finanzas',ReporteFinanzasCursosViews.as_view(), name="cursos_finanzas"),
    path('reportes/curso_torta',ReporteCursosViews.as_view(), name="curso_torta") ,
]

sec2/apps/users/urls.py
from django.shortcuts import render
from .views import CustomLoginView, CreacionUsuarios,cerrar_session, UserListView, actualizar_permisos
from django.urls import path

app_name = "users"

urlpatterns = [
  path('login/', CustomLoginView.as_view(), name='login'),
  path('registrar_usuarios/', CreacionUsuarios.as_view(), name='user_register'),
  path('listar_usuarios/', UserListView.as_view(), name='user_listado'),
  path('actualizar_permisos/<int:pk>',actualizar_permisos,name="actualizar_permisos"),
  path('cerrar_session/',cerrar_session,name='cerrar_session'),

   ]

sec2/sec2/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


handler403 = custom_403_view
urlpatterns = [
    
    #PRINCIPALES
    
    path('', home, name="login"),
    path('admin/', admin.site.urls),
    path('home/', home, name="home"),

    #APLICACIONES
    path('home/app_afiliados/',include('apps.afiliados.urls')),
    path('home/app_cursos/',include('apps.cursos.urls')),
    path('home/app_personas/',include('apps.personas.urls')),
    path('home/app_alquileres/',include('apps.alquileres.urls')),
    path('home/app_reportes/',include('apps.reportes.urls')),

    path('',include('apps.users.urls')),
    path('select2/', include('django_select2.urls')),
    path('selectable/', include('selectable.urls')),

    path('manual_usuario/', abrirManualUsuario, name="manual_usuario"),
    path('documentacion_tecnica/', abrirDocumentacionTecnica, name="documentacion_tecnica"),


]

sec2/templates/afiliado_historial.html
{% extends 'home_afiliado.html' %}
{% load static %}

{% block container %}

  {% block nav_top %}
  {% include 'nav_top.html' %}
  {% endblock %}
  
	<div class="wrapper d-flex align-items-stretch">
    {% block nav_lateral %}
      {% include 'nav_lateral_afiliado_historial.html' %}
    {% endblock %}
    
    <div id="content" class="p-4 p-md-5 pt-5">
      {% block dinamica %}
      {% include 'home_afiliado.html' %}
      {% endblock %}
    </div>
  </div>
  {% endblock %}

  {% block nav_lateral_filtro %}
  {% endblock %}

  {% block extrajs %}
  {% endblock %}
  

sec2/templates/footer.html
<style>
  .footer {
    background-color: slategray;
    color: #fff;
    padding: 0;
    position: fixed;
    bottom: 0;

  }

  .bandera{
    width: 1.5%;

  }

</style>

{% load static %}

<div class="footer text-center">
      © 2024 Sindicato Empleados de Comercio | SEC2 | @Todos los derechos reservados
      <img class="bandera" src="{% static 'images/argentina.png' %}" alt="Descripción de la imagen">
      <img class="bandera" src="{% static 'images/chile.png' %}" alt="Descripción de la imagen">
      <img class="bandera" src="{% static 'images/peru.png' %}" alt="Descripción de la imagen">
</div>

sec2/templates/home_afiliado.html
{% extends 'base.html' %}

{% load static %}

{% block extracss %}
  <link href="{% static 'Libs/css/home.css' %}" rel="stylesheet" />
  <link href="{% static 'Libs/css/nav_top.css' %}" rel="stylesheet" />
  {% block extracss_intermedia %}

  {% endblock %}
{% endblock %}

{% block container %}
  <div id="wrapper">
    <div id="sidebar">
      {% block nav_lateral %}
        {% include 'nav_afiliado.html' %}
      {% endblock %}
      
      <!-- Este div se mostrará al final del #sidebar -->
      <div id="messages-container">
        {% include 'message.html' %}
      </div>
    </div>
    <div id="content">
      {% include 'nav_top.html'  %}
      
      {% block dinamica %}
        {% include 'index.html' %}
      {% endblock %}
      
    </div>
  </div>
{% endblock %}  

{% block extrajs %}
  <script src="{% static 'Libs/js/home_afiliado.js' %}"></script>
  
  {{ buscador.media.js }}
  
  {% block extrajs_intermedia %}
  {% endblock %}
{% endblock %}

sec2/templates/home_curso.html
{% extends 'base.html' %}

{% load static %}

{% block extracss %}
  <link href="{% static 'Libs/css/home.css' %}" rel="stylesheet" />
  <link href="{% static 'Libs/css/nav_top.css' %}" rel="stylesheet" />
  {% block extracss_intermedia %}
  {% endblock %}
{% endblock %}

{% block container %}
  <div id="wrapper">
    <div id="sidebar">
      {% block nav_lateral %}
        {% include 'nav_curso.html' %}
      {% endblock %}

      <!-- Este div se mostrará al final del #sidebar -->
      <div id="messages-container">
        {% include 'message.html' %}
      </div>
    </div>

    <div id="content">
      {% include 'nav_top.html' %}
      {% block dinamica %}
        {% include 'index.html' %}
      {% endblock %}
    </div>
  </div>
{% endblock %}

{% block extrajs %}
  <script src="{% static 'Libs/js/home_afiliado.js' %}"></script>

  {% block extrajs_intermedia %}
  {% endblock %}
{% endblock %}

sec2/templates/message.html
{% if messages %}
  {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
      <span>{{ message|safe }}</span>
      {% if form.errors %}
        <br />
        {% for error in form.non_field_errors %}
          {{ error|safe }}
        {% endfor %}
      {% endif %}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endfor %}
{% endif %}

sec2/templates/nav_afiliado.html
{% load static %}

{% block extracss %}
  <link href="{% static 'Libs/css/nav_principal.css' %}" rel="stylesheet" />
  <link href="{% static 'Libs/css/nav_curso.css' %}" rel="stylesheet" />
{% endblock %}

<div class="menu" id="  ">
  <br />
  <h3 class="titulo-menu">AFILIADOS</h3>
  <ul class="menu">
    <li>
      <a href="/home" id="mostrarMenuPrincipal"><i class="fa-solid fa-arrow-left-long"></i> Menu principal</a>
    </li>
  </ul>
</div>

<hr />
<div class="menu">

  <button class="submenu-toggle" data-submenu="curso">
    <div class="button-content">
        <span> <i class="fa-regular fa-user"></i> Afiliado</span>
    </div>
    <i class="fa-solid fa-caret-down"></i>
</button>
  <ul class="submenu" id="curso-submenu">
    <li>
      <a href="{% url 'afiliados:afiliado_crear' %}"><i class="fa-solid fa-plus"></i> Alta afiliado</a>
    </li>
    <li>
      <a href="{% url 'afiliados:afiliado_listar' %}"><i class="fa-solid fa-list"></i> Lista de afiliados</a>
    </li>
  </ul>
</div>

<hr />

<div class="menu">
  <button class="submenu-toggle" data-submenu="profesor">
    <div class="button-content">
      <span><i class="fa-solid fa-users"></i> Grupo Familiar</span>
    </div>
    <i class="fa-solid fa-caret-down"></i>
  </button>
  
  <ul class="submenu" id="curso-submenu">
    <li>
      <a href="{% url 'afiliados:crear_familiar_directo' %}"><i class="fa-solid fa-plus"></i> Alta Familiar</a>
    </li>
    <li>
      <a href="{% url 'afiliados:grupo_familiar_listar' %}"><i class="fa-solid fa-list"></i> Lista de familiares</a>
    </li>
  </ul>
</div>
<hr />

<div class="menu">
  <!-- Botón desplegable para Pago -->
  <button class="submenu-toggle" data-submenu="pago">
    <div class="button-content">
      <span>
        <i class="fa-solid fa-dollar-sign"></i> 
        Pago de Cuotas
      </span>
    </div>
    <i class="fa-solid fa-caret-down"></i>
  </button>

  <ul class="submenu" id="pago-submenu">
    <li>
      <a href="{% url 'afiliados:pagar_cuota_sindical' %}"><i class="fa-solid fa-sack-dollar"></i> Cuota sindical</a>
    </li>
    <li>
      <a href="{% url 'afiliados:pago_cuota_listado' %}"><i class="fa-solid fa-list"></i> Lista de cuotas</a>
    </li>
  </ul>
</div>
<hr />

{% comment %} BOTON DE SERVICIO {% endcomment %}
<a class="enlace" id="enlaceReporte" href="{% url 'reportes:afiliados_historico' %}"><i class="fa-solid fa-chart-column"></i> Reportes</a>


{% include 'documentacion_info.html' %}






  {% block extrajs %}
  <script src="{% static 'Libs/js/nav_curso.js' %}"></script>
{% endblock %}

sec2/templates/nav_alquiler.html
{% load static %}

{% block extracss %}
<link href="{% static 'Libs/css/nav_principal.css' %}" rel="stylesheet" />
<link href="{% static 'Libs/css/nav_curso.css' %}" rel="stylesheet" />
{% endblock %}

<div class="menu" id="menu_afiliado_principal">
  <br />
  <h3 class="titulo-menu">SALONES</h3>
  <ul class="menu">
    <li>
      <a href="/home" id="mostrarMenuPrincipal"><i class="fa-solid fa-arrow-left-long"></i> Menu principal</a>
    </li>
  </ul>
</div>
<hr>

<div class="menu">
  <button class="submenu-toggle" data-submenu="curso" style="background-color: #124076;">
    <div class="button-content">
      <span><i class="fa-solid fa-file-contract"></i>  Alquiler </span>
    </div>
    <i class="fa-solid fa-caret-down"></i>
  </button>
  <ul class="submenu" id="profesor-submenu">
    <li>
      <a href="{% url 'alquiler:alquiler_listar' %}"><i class="fa-solid fa-plus item-subMenu"></i> Crear alquiler</a>
    </li>
  </ul>
</div>
<hr>

<div class="menu">
  <!-- Botón desplegable para Curso -->
  <button class="submenu-toggle" data-submenu="curso">
    <div class="button-content">
    <span><i class="fa-solid fa-person-shelter"></i> Encargado </span>
  </div>

    <i class="fa-solid fa-caret-down"></i>
  
  </button>
  <ul class="submenu" id="curso-submenu">
    <li>
      <a href="{% url 'alquiler:encargado_alta' %}"><i class="fa-solid fa-plus item-subMenu"></i> Alta de encargado</a>
    </li>
    <li>
      <a href="{% url 'alquiler:encargado_listar' %}"><i class="fa-solid fa-list item-subMenu"></i> Lista encargados</a>
    </li>
  </ul>
</div>
<hr>

<div class="menu">
  <!-- Botón desplegable para Salon -->
  <button class="submenu-toggle" data-submenu="profesor">
    <div class="button-content">

    <span> <i class="fa-solid fa-house"></i> Salon </span>
    </div>
    
    <i class="fa-solid fa-caret-down"></i>
  
  </button>
  <ul class="submenu" id="curso-submenu">
    <li>
      <a href="{% url 'alquiler:salon_crear' %}"><i class="fa-solid fa-plus item-subMenu"></i> Crear salon</a>
    </li>
    <li>
      <a href="{% url 'alquiler:salon_listar' %}"><i class="fa-solid fa-list item-subMenu"></i> Lista de salones</a>
    </li>
  </ul>
</div>
<hr>

{% comment %} BOTON DE SERVICIO {% endcomment %}
<a class="enlace" id="enlaceActividad" href="{% url 'alquiler:gestion_servicio' %}"><i class="fa-solid fa-clipboard-list"></i> Servicio</a>

<hr>
{% comment %} BOTON DE SERVICIO {% endcomment %}
<a class="enlace" id="enlaceReporte" href="{% url 'reportes:alquileres_por_mes' %}"><i class="fa-solid fa-chart-column"></i> Reportes</a>


{% include 'documentacion_info.html' %}

{% block extrajs %}
  <script src="{% static 'Libs/js/nav_salon.js' %}"></script>
{% endblock %}

sec2/templates/nav_filtro.html
{% load static %}
{% load crispy_forms_tags %}

{% block extracss %}
  <link href="{% static 'Libs/css/nav_filtro.css' %}" rel="stylesheet" />
{% endblock %}

<nav id="filtro">
  <div class="p-4">
    <h2 id="titulo-filtro">Filtros</h2>
    {% crispy filtros %}
    
  </div>
</nav>
<script type="text/javascript" src="{% static 'Libs/js/jquery-1.11.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'Libs/js/jquery-iu.js' %}"></script>
<script type="text/javascript" src="{% static 'selectable/js/jquery.dj.selectable.js' %}"></script>
<link href="{% static 'selectable/css/dj.selectable.css' %}" type="text/css" media="all" rel="stylesheet">

{% block extrajs %}

{% endblock %}

sec2/templates/nav_gestion_usuarios.html
{% load static %}

{% block extracss %}
<link href="{% static 'Libs/css/nav_principal.css' %}" rel="stylesheet" />
<link href="{% static 'Libs/css/nav_curso.css' %}" rel="stylesheet" />
{% endblock %}

<div class="menu" id="menu_afiliado_principal">
  <br />
  <h3 class="titulo-menu">USUARIOS</h3>
  <ul class="menu">
    <li>
      <a href="/home" id="mostrarMenuPrincipal"><i class="fa-solid fa-arrow-left-long"></i> Menu principal</a>
    </li>
  </ul>

  <a class="enlace" id="enlaceActividad" href="{% url 'users:user_register' %}">
    <i class="fa-solid fa-user-plus"></i> 
    Crear Usuario</a>
  
  <hr>
  
  <a class="enlace" id="enlaceReporte" href="{% url 'users:user_listado' %}">
    <i class="fa-solid fa-list "></i> 
    Listado de usuarios
  </a>
</div>

<hr>
{% include 'documentacion_info.html' %}

{% comment %}{% block extrajs %}
  <script src="{% static 'Libs/js/nav_salon.js' %}"></script>
{% endblock %}{% endcomment %}

sec2/templates/nav_lateral_afiliado_historial.html
{% load static %}

{% block extracss %}
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet" />
  <link href="{% static 'Libs/css/nav_lateral.css' %}" rel="stylesheet" />
{% endblock %}

<nav id="sidebar">
  <div class="custom-menu">
    <button type="button" id="sidebarCollapse" class="btn btn-primary" style="z-index:10"><span class="sr-only">Toggle Menu</span></button>
  </div>
  <div class="p-4">
    <h1><a href="{% url 'afiliados:index' %}" class="logo">HISTORIAL</a></h1>
    <h1><a href="{% url 'home' %}" class="logo"><span>Volver a la Gestión de Afiliados</span></a></h1>
    <ul class="list-unstyled components mb-5">
      <li class="active">
        <a href="{% url 'afiliados:afiliado_crear' %}"><span class="fa fa-arrow-circle-up mr-3"></span>Datos Afiliados</a>
      </li>
      <li class="active">
        {% comment %} <a href="{% url 'afiliados:afiliado_listar' %}"><span class="fa fa-id-badge mr-3"></span>Grupo Familiar</a> {% endcomment %}
      </li>
      <li class="active">
        {% comment %} <a href="{% url 'afiliados:afiliado_listar' %}?estado=1"><span class="fa fa-check-square mr-3"></span>Cursos realizados</a> {% endcomment %}
      </li>
      <li class="active">
        {% comment %} <a href="{% url 'afiliados:afiliado_listar' %}?estado=1"><span class="fa fa-check-square mr-3"></span>Capacitaciones realizadas</a> {% endcomment %}
      </li>
    </ul>

    <div class="mb-5">
      <br /><br /><br /><br /><br /><br /><br /><br />
    </div>

    <div class="footer">
      <p>© 2022 Sindicato Empleados de Comercio | SEC2. Todos los derechos reservados</p>
    </div>
  </div>
</nav>

{% block extrajs %}
  <!-- !YA ESTA EN EL BASE LOS SIGUIENTES SCRIPT -->
  <!--  <script src="{% static 'Libs/js/jquery.min.js' %}"></script>
<script src="{% static 'Libs/js/popper.js' %}"></script>
<script src="{% static 'Libs/js/main.js' %}"></script>  -->
{% endblock %}

sec2/templates/nav_principal.html
{% load static %}

{% block extracss %}
  <link href="{% static 'Libs/css/nav_principal.css' %}" rel="stylesheet" />
  {% comment %} <link href="{% static 'Libs/css/nav_afiliado.css' %}" rel="stylesheet" /> {% endcomment %}
  <link href="{% static 'Libs/css/nav_curso.css' %}" rel="stylesheet" />
{% endblock %}


<div class="menu" id="menu_principal">
  <br>
  <h3 class="titulo-menu">SEC 2</h3>
  <ul class="menu">
    {% if 'permission_gestion_afiliado' in permisos %}
    <li>
      <a href="#" id="mostrarMenuAfiliado">
        <i class="fa-solid fa-person-dress"></i>
        Gestión de Afiliados</a>
    </li>
    {% endif %}
    {% if 'permission_gestion_curso' in permisos %}
    <li>
      <a href="#" id="mostrarMenuCurso">
        <i class="fa-solid fa-graduation-cap"></i> 
        Gestión de Cursos</a>
    </li>
    {% endif %}
      {%if 'permission_gestion_alquiler' in permisos %} 
    <li>
      <a href="#" id="mostrarMenuSalon">
        <i class="fa-solid fa-person-shelter"></i>
         Gestión de Salon</a>
    </li>
     {% endif %} 
     {% if 'permission_gestion_usuario' in permisos %} 
    <li>
       <a href="{% url 'users:user_register' %}" id="mostrarMenuSalon"> 
        <a href="#" id="mostrarMenuUsers">
        <i class="fa-solid fa-users-gear"></i>
         Gestión de Usuarios</a>
    </li>
     {% endif %}  
    {% include 'documentacion_info.html' %}

    {% comment %} {% endif %} {% endcomment %}
 
  </ul>
  




  </div>
<div id="menu_afiliado_principal" style="display: none;">
  <!-- Menú Afiliados -->
  {% include 'nav_afiliado.html' %}
</div>

<div id="menu_curso_principal" style="display: none;">
  <!-- Menú Cursos -->
  {% include 'nav_curso.html' %}
</div>

<div id="menu_salon_principal" style="display: none;">
  <!-- Menú Cursos -->
  {% include 'nav_alquiler.html' %}
</div>

<div id="menu_usuarios_principal" style="display: none;">
  <!-- Menú Usuarios -->
  {% include 'nav_gestion_usuarios.html' %}
</div>

{% block extrajs %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'Libs/js/nav_principal.js' %}"></script>

<script src="{% static 'Libs/js/abrir_documetacion.js' %}"></script>

{% endblock %}

sec2/templates/nav_top.html
{% load static %}
{% load crispy_forms_tags %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  
  <div class="container-fluid">
    <div class="mx-auto">
      <form class="d-flex" role="search" method="get" style="width: 120%;">
        {{filter_form.dni}}
        <button id="submit-button" class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>

      </form>
    </div>


  <div class="btn-group" style="margin-right: 1%;">
    
    <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false" 
    >
      <i class="fa-regular fa-user"></i> 
      Hola, {{ user }}
    </button>
    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg-start">
      <li>
        <a class="dropdown-item" type="button" href="{% url 'users:cerrar_session' %}" > 
          <i class="fa-solid fa-lock"></i>
          Cerrar Sesión</a>
      </li>
    </ul>
  </div>
</nav>

<script type="text/javascript" src="{% static 'Libs/js/jquery-1.11.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'Libs/js/jquery-iu.js' %}"></script>
<script type="text/javascript" src="{% static 'selectable/js/jquery.dj.selectable.js' %}"></script>
<link href="{% static 'selectable/css/dj.selectable.css' %}" type="text/css" media="all" rel="stylesheet">

sec2/templates/persona_detalle.html
{% comment %} DNI - CUIT - NACIMIENTO {% endcomment %}
<div class="row row-cols-2 row-cols-sm-4 row-cols-md-6">
  <div class="col">
    <p class="negrita">Dni:</p>
  </div>
  <div class="col">
    <p>{{ persona.dni }}</p>
  </div>

  <div class="col">
    <p class="negrita">Cuit:</p>
  </div>
  <div class="col">
    <p>{{ persona.cuil }}</p>
  </div>

  <div class="col">
    <p class="negrita">Nacimiento:</p>
  </div>
  <div class="col">
    <p>{{ persona.fecha_nacimiento }}</p>
  </div>
</div>

{% comment %} NOMBRE - APELLIDO - CELULAR {% endcomment %}
<div class="row row-cols-2 row-cols-sm-4 row-cols-md-6">
  <div class="col">
    <p class="negrita">Nombre:</p>
  </div>
  <div class="col">
    <p>{{ persona.nombre }}</p>
  </div>

  <div class="col">
    <p class="negrita">Apellido:</p>
  </div>
  <div class="col">
    <p>{{ persona.apellido }}</p>
  </div>

  <div class="col">
    <p class="negrita">Celular:</p>
  </div>
  <div class="col">
    <p>{{ persona.celular }}</p>
  </div>
</div>

{% comment %} PAIS - ESTADO - MAIL {% endcomment %}
<div class="row row-cols-2 row-cols-sm-4 row-cols-md-6">
  <div class="col">
    <p class="negrita">Nacionalidad:</p>
  </div>
  <div class="col">
    <p>{{ persona.get_nacionalidad_display }}</p>
  </div>
  <div class="col">
    <p><strong>Correo:</strong>
    {{ persona.mail }}</p>
  </div>
  <div class="col">
    </div>
  <div class="col">
    <p class="negrita">Estado Civil:</p>
  </div>
  <div class="col">
    <p>{{ persona.get_estado_civil_display }}</p>
  </div>
</div>

sec2/templates/tabla_persona_cabecera.html
<th>Dni</th>
<th>Nombre</th>