sec2/apps/afiliados/urls.py
# Importaciones del sistema
from django.urls import path
# Importaciones locales
from selectable import urls as selectable_urls
from .views import *
from django.contrib.auth.decorators import login_required, permission_required



app_name = "afiliados"

urlpatterns = [
    path('',index, name="index"),

    #AFILIADO
    path('afiliados/afiliado/crear/',AfiliadoCreateView.as_view(), name="afiliado_crear"),
    path('afiliados/afiliado/<int:pk>',AfiliadoDetailView.as_view(), name="afiliado_detalle"),
    path('afiliados/afiliado/<int:pk>/editar', AfiliadoUpdateView.as_view(), name="afiliado_actualizar"),
    path('afiliados/listar',AfiliadosListView.as_view(), name="afiliado_listar"),
    path('afiliados/afiliado/<int:pk>/<str:accion>/<str:origen>/', afiliado_afiliar_desafiliar, name="afiliado_afiliar_desafiliar"),
    #ALTA GRUPO FAMILIAR (accedido desde afiliado)
    path('afiliado/<int:pk>/grupoFamiliar/crear', FamiliaCreateView.as_view(), name="crear_familiar"),

    #RELACION AFILIADO-GRUPO FAMILIAR
    path('grupofamiliar/listado', RelacionFamiliarListView.as_view(), name="grupo_familiar_listar"),

    #GRUPO FAMILIAR
    path('grupofamiliar/crear', alta_familiar, name="crear_familiar_directo"),
    path('afiliado/<int:pk>/grupoFamiliar/familia/<int:familiar_pk>', FamiliarDetailView.as_view(), name="familiar_detalle"),
    path('afiliado/<int:pk>/grupoFamiliar/familia/<int:familiar_pk>/editar/', FamiliarUpdateView.as_view(), name="familiar_editar"),
    path('afiliado/<int:pk>/grupoFamiliar/familia/<int:familiar_pk>/eliminar', familiar_eliminar, name="familiar_eliminar"),

    # path('afiliado/grupoFamiliar/familia/<int:familiar_pk>/editar', FamiliarUpdateView_.as_view(), name="familiar_editar_"),
    #ACCEDIDOS DESDE LA APLICACION DE CURSOS
    # path('afiliado/grupoFamiliar/familia/<int:familiar_pk>', FamiliarDetailVentanaNuevaView_.as_view(), name="familiar_detalle_"),

    #GENERAR PDF
    path('pago/afiliado/afiliado/<int:pk>/generarnota', confeccionarNota ,name="confeccionar_nota"),
    path('pago/afiliado/cuotas', PagoCuotaCreateView.as_view() ,name="pagar_cuota_sindical"),
    
    path('pago/listado', PagoCuotaListView.as_view() ,name="pago_cuota_listado"),
    path('pago/ruta_para_actualizar_afiliados/', obtener_afiliados_por_cuit_empleador, name='ruta_para_actualizar_afiliados'),
    
    path('pago/afiliado/actualizar', cuota_sindical_actualizar_estado ,name="actualizar_estado"),
 
]

sec2/apps/alquileres/urls.py
from django.urls import path
from .views import *
from . import views

app_name="alquiler"


urlpatterns = [
    path('',index, name="index"),
    
    # ENCARGADO
    path('encargados/listado',EncargadoListView.as_view(), name="encargado_listar"),
    path('encargados/encargado/crear/',EncargadoCreateView.as_view(), name="encargado_alta"),
    path('encargados/encargado/<int:pk>', EncargadoDetailView.as_view(), name="encargado_detalle"),
    path('encargados/encargado/<int:pk>/editar', EncargadoUpdateView.as_view(), name="encargado_editar"),

    # SERVICIO
    path('servicios/', GestionServicioView.as_view(), name="gestion_servicio"),
    path('servicio/servicio/<int:pk>/', ServicioDetailView.as_view(), name='servicio_detalle'),
    path('aulas/aula/<int:pk>/editar', ServicioUpdateView.as_view(), name="servicio_editar"),
    path('aulas/aula/<int:pk>/eliminar', servicio_eliminar, name="servicio_eliminar"),

    # SALON
    path('salones',SalonesListView.as_view(), name="salon_listar"),
    path('salones/salon/crear/',SalonCreateView.as_view(), name="salon_crear"),
    path('salones/salon/<int:pk>',SalonDetailView.as_view(), name="salon_detalle"),
    path('salones/salon/<int:pk>/editar', SalonUpdateView.as_view(), name="salon_actualizar"),
    path('salones/salon/<int:pk>/eliminar', salon_eliminar, name="salon_eliminar"),

    # ALQUILER
    path('alquileres/',AlquilieresListView.as_view(), name="alquiler_listar"),
    path('alquileres/alquiler/crear',AlquilerCreateView.as_view(), name="alquiler_crear"),
    path('alquileres/alquiler/<int:pk>',AlquilerDetailView.as_view(), name="alquiler_detalle"),
    # path('modificar/<int:pk>', AlquilerUpdateView.as_view(), name="alquiler_actualizar"),
    path('alquileres/alquiler/<int:pk>/agregarlistaespera',agregar_lista_espera, name="agregar_lista_espera"),
    path('alquileres/alquiler/<int:pk>/reemplazarinquilino', reemplazar_inquilino, name="reemplazar_inquilino"),
    path('alquileres/alquiler/<int:alquiler_pk>/listaespera/quitar/<int:afiliado_pk>', quitar_lista_alquiler, name="quitar_lista_alquiler"),

    path('alquileres/alquiler/<int:pk>/eliminar', alquiler_eliminar, name="alquiler_eliminar"),
    
    # PAGO DE ALQUILER
    path('crearPago/',PagoAlquilerCreateView.as_view(), name="pagar_alquiler_crear"),

]

sec2/sec2/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


handler403 = custom_403_view
urlpatterns = [
    
    #PRINCIPALES
    
    path('', home, name="login"),
    path('admin/', admin.site.urls),
    path('home/', home, name="home"),

    #APLICACIONES
    path('home/app_afiliados/',include('apps.afiliados.urls')),
    path('home/app_cursos/',include('apps.cursos.urls')),
    path('home/app_personas/',include('apps.personas.urls')),
    path('home/app_alquileres/',include('apps.alquileres.urls')),
    path('home/app_reportes/',include('apps.reportes.urls')),

    path('',include('apps.users.urls')),
    path('select2/', include('django_select2.urls')),
    path('selectable/', include('selectable.urls')),

    path('manual_usuario/', abrirManualUsuario, name="manual_usuario"),
    path('documentacion_tecnica/', abrirDocumentacionTecnica, name="documentacion_tecnica"),


]

sec2/apps/alquileres/models.py
import datetime
from unittest.util import _MAX_LENGTH
from django.db import models
from apps.personas.models import *
from apps.afiliados.models import *
from utils.choices import LOCALIDADES_CHUBUT
from apps.personas.models import Rol, Persona
from django.db.models import Count
from django import forms
from datetime import datetime

class Servicio (models.Model):
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.nombre}"
    
class Encargado (Rol):
    TIPO=ROL_TIPO_ENCARGADO
    dictados = models.ManyToManyField(Dictado, related_name="encargados", blank=True)

    def __str__(self):
        return f"{self.persona.dni} | {self.persona.nombre} {self.persona.apellido}"
Rol.register(Encargado)

class Salon(models.Model):
    TIPO_SALON=[
        (1,'Polideportivo'),
        (2,'Multiuso')
    ]
    nombre = models.CharField(max_length=30)
    localidad= models.CharField(max_length =25,choices = LOCALIDADES_CHUBUT)
    direccion=models.CharField(max_length=50)
    capacidad=models.PositiveIntegerField()
    encargado=models.ForeignKey(Encargado, related_name="salon", on_delete=models.CASCADE)
    precio=models.DecimalField(help_text="costo del alquiler", max_digits=10, decimal_places=2)
    fechaBaja= models.DateField(null=True,blank=False)
    tipo_salon = models.PositiveSmallIntegerField(choices=TIPO_SALON)
    servicios=models.ManyToManyField(Servicio, blank=True) 
    
    def __str__(self):
        return f"{self.nombre} | Capacidad: {self.capacidad} personas"
    

class Alquiler(models.Model):
    class Meta:
         permissions = [("permission_gestion_alquiler", "Control total alquiler")]

         

    ESTADOS = (
        (1, 'Confirmado'), # esta pactado la fecha 
        (2, 'En curso'),  #es la fecha actual
        (3, 'Finalizado'), # se reaizo el alquiler
        (4, 'Cancelado'), # se cancelo antes de que se realice
    )

    TURNOS=[

        ('Mañana','Mañana'),
        ('Noche','Noche')
    ]
    cambio_inquilino = models.BooleanField(default=False)  # Campo booleano para indicar si se realizó un cambio de inquilino
    estado = models.IntegerField(choices=ESTADOS, default=1)
    afiliado=models.ForeignKey(Afiliado, related_name="alquileres", on_delete=models.CASCADE)
    salon=models.ForeignKey(Salon, related_name="alquileres", on_delete=models.CASCADE)
    fecha_solicitud=models.DateTimeField(auto_now_add=True, null=True, blank=True)
    fecha_alquiler=models.DateTimeField(null=True, blank=True) 
    turno=models.CharField(max_length=50, choices=TURNOS) #verificar bien la forma de los turnos
    seguro=models.DecimalField(help_text="costo del alquiler", max_digits=10, decimal_places=2)
    lista_espera=models.ManyToManyField(Afiliado, blank=True)
    fechaBaja= models.DateField(null=True,blank=False)
    #crear lista de espera para agregar afiliado interesado que solamente mostrara para el afiliado que esta en espera, el sistea no se encarga de la actulizacion del cliente de manera automatica a la hora actulizar el cliente que contrata el salon
    #servicios[1..n] no se detallan los servicios "extras" que ofrece el sindicato porque solamente hace de nexo entre la empresa que lo ofrece y el afiliado

    def __str__(self):
        return f"{self.fecha_alquiler, self.turno, self.afiliado.persona, self.salon}"
    
    def verificar_existencia_alquiler(self, salon, fecha_alquiler, turno):
        # Verificar si existe algún alquiler que cumple con las condiciones dadas
        alquiler_existente = Alquiler.objects.filter(salon=salon, fecha_alquiler=fecha_alquiler, turno=turno, estado=1).exists()
       # Devolver True si existe al menos un alquiler que cumple con las condiciones
        return alquiler_existente

    def fecha_valida(fecha):
            #Verifica que la fecha sea mayor a la de hoy
            hoy = datetime.today()
                
            if fecha.date() > hoy.date():
                return True
            else:
                return False
            
            
class Pago_alquiler(models.Model):
    alquiler=models.ForeignKey(Alquiler, related_name="pagos", on_delete=models.CASCADE)
    fecha_pago=models.DateTimeField(auto_now_add=True, null=True, blank=True)
    FORMA_PAGO=[
        ('total','Total'),
        ('cuota','Cuota')
    ]
    forma_pago = models.CharField(max_length=30, choices=FORMA_PAGO)
    #agregar las dos formas de pago total(no importa si es contado o tarjeta) o cuota (no  se realiza en el sistema la forma de pago y como se actualiza)
    #ver si el sistema entrega comprobante de pago

    def alquileres_sin_pago():
    # Obtener todos los alquileres que no tienen ningún pago asociado
        alquileres_sin_pagos = Alquiler.objects.annotate(num_pagos=Count('pagos')).filter(num_pagos=0)
        return alquileres_sin_pagos

sec2/apps/cursos/views/pago_views.py
# from ..models import Pago_alumno
# from ..forms.pago_alumno_forms import *
# from django.views.generic.edit import CreateView
# from django.urls import reverse_lazy

# class PagoAlumnoCreateView(CreateView):
#     model = Pago_alumno
#     form_class = FormularioPagoAlumno
#     template_name = 'otro/pago_alumno_form.html'  
#     success_url = reverse_lazy('cursos:cursos')
    
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['titulo'] = "Listado de profesores"
#         return context

sec2/apps/alquileres/templates/alquiler_detail.html
{% extends 'detalle_listado.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block detalle %}
<h3> Datos del afiliado </h3>
{% include "persona_detalle.html" with persona=alquiler.afiliado.persona %}

<h3> Datos del alquiler </h3>

<div class="row row-cols-2 row-cols-sm-4 row-cols-md-6">
  <div class="col">
    <p class="negrita"> Salón: </p>
  </div>
  <div class="col">
    <p>{{ alquiler.salon }}</p>
  </div>

  <div class="col">
    <p class="negrita">Fecha de solicitud: </p>
  </div>
  <div class="col">
    <p>{{ alquiler.fecha_solicitud }}</p>
  </div>

  <div class="col">
    <p class="negrita">Fecha de alquiler: </p>
  </div>
  <div class="col">
    <p>{{ alquiler.fecha_alquiler|date:"j F Y" }}</p>
  </div>
</div>


<div class="row row-cols-2 row-cols-sm-4 row-cols-md-6">
  <div class="col">
    <p class="negrita"> Turno: </p>
  </div>
  <div class="col">
    <p>{{ alquiler.turno }}</p>
  </div>

  <div class="col">
    <p class="negrita">Seguro: </p>
  </div>
  <div class="col">
    <p>${{ alquiler.seguro }}</p>
  </div>
  <div class="col">
    <p class="negrita">Estado: </p>
  </div>
  <div class="col">
    <p class="status">
      {% if alquiler.estado == 1 %} <span class="active-status">Confirmado</span>
      {% elif alquiler.estado == 2 %}  <span class="active-status">EN CURSO</span>
      {% elif alquiler.estado == 3 %} <span class="inactive-status">FINALIZADO</span>
      {% elif alquiler.estado == 4 %} <span class="moroso-status">Cancelado</span>      
      {% endif %}
  </p>
  </div>
</div>

<div class="row row-cols-2 row-cols-sm-4 row-cols-md-6">
  <div class="col">
    <p class="negrita">Tipo de afiliado : </p>
  </div>
  <div class="col">
    <p>
      {% if not alquiler.cambio_inquilino %} Original 
      {% else %} Rectificado
      {% endif %}
    </p>
  </div>
  <div class="col">
    <p class="negrita"> Fecha de pago: </p>
  </div>
  <div class="col">
    <p>{{ pago.fecha_pago }}</p>
  </div>
  <div class="col">
    <p class="negrita">Forma de pago: </p>
  </div>
  <div class="col">
    <p>{{ pago.forma_pago }}</p>
  </div>
</div>
{% endblock %}


{% block botones %}

<div class="col">
  <a href="{% url 'alquiler:alquiler_listar' %}" class="btn btn-sm btn-secondary btn-detalle">
  <i class="fa-solid fa-arrow-left"></i> Ir al calendario
  </a>
</div>

<div class="col">
  {% if not alquiler.fechaBaja %}
    {% comment %} <a href="{% url 'afiliados:afiliado_actualizar' alquiler.pk %}" class="btn btn-sm btn-primary btn-detalle "><i class="fas fa-pencil-alt"></i> Modificar</a> {% endcomment %}
  {% endif %}
</div>

<div class="col"> 
  <a href="{% url 'afiliados:afiliado_detalle' alquiler.afiliado.pk %}" class="btn btn-sm btn-info btn-detalle">
    <i class="fa-regular fa-user"></i> Ir al Afiliado
  </a>
</div>

<div class="col">
  {% if not alquiler.fechaBaja and alquiler.lista_espera.exists %}
      <a href="{% url 'alquiler:reemplazar_inquilino' alquiler.pk %}" class="btn btn-primary btn-sm btn-detalle"><i class="fa-solid fa-repeat"></i> Cambiar de afiliado</a>            
  {% endif %}
</div>

<div class="col">
  {% if not alquiler.fechaBaja %}
    <button type="button" class="btn btn-danger btn-sm btn-detalle" data-bs-toggle="modal" data-bs-target="#exampleModal_eliminar_alquiler"><i class="fa-regular fa-circle-down"></i> Dar de Baja</button>
    {% include 'modal_confirm_baja_alquiler.html' %}
  {% endif %}
</div>

{% endblock %}

{% block listado_asociado %}
<div class="container-sm">
  <h3 class="subtitulo">{{ tituloListado1 }}</h3>
  {% if not alquiler.fechaBaja %}
    <a href={% url 'alquiler:agregar_lista_espera' alquiler.pk %} 
    class="btn btn-warning btn-sm btn-detalle" 
    onclick="openOrFocusWindow(this.href, 'Lista de espera', 250, 300); return false;">
    <i class="fa-solid fa-list"></i>
    Agregar lista espera
  </a>
  {% endif %}

  {% if alquiler.lista_espera.all %}
  
  <table class="table table-sm table-hover">
    <thead>
        <tr>
          <th>#</th>
          {% include 'tabla_persona_cabecera.html' %}
          <th>N° Contacto</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for afiliado in alquiler.lista_espera.all %}
        <tr>
          <td class="negrita">{{ forloop.counter }}</td>
          {% include 'tabla_persona_cuerpo.html' with persona=afiliado.persona %}
          <td>{{ afiliado.persona.celular }}</td>

          <td class="text-end">
            <a href="{% url 'afiliados:afiliado_detalle' afiliado.pk %}" class="btn btn-info btn-sm btn-detalle"><i class="fa-regular fa-eye"></i> Detalle</a>            
            {% if not alquiler.fechaBaja %}
            <a href="{% url 'alquiler:quitar_lista_alquiler' alquiler_pk=alquiler.pk afiliado_pk=afiliado.pk %}" class="btn btn-outline-danger btn-sm btn-detalle"><i class="fa-regular fa-trash-can"></i> Quitar</a>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
  </table>

    {% else %}
    <p>No existen afiliados en lista de espera</p>
  {% endif %}

</div>
{% endblock %}



{% block extrajs_intermedia %}
<script>
  var listaEsperaWindow = null;

  function openOrFocusWindow(url, name, width, height) {
    // Verifica si la ventana ya está abierta
    if (listaEsperaWindow && !listaEsperaWindow.closed) {
      // Si está abierta, enfócala
      listaEsperaWindow.focus();
    } else {
      // Si no está abierta, abre una nueva ventana
      listaEsperaWindow = window.open(url, name, 'width=' + width + ',height=' + height);
    }
  }
</script>
{% endblock %}

sec2/apps/alquileres/templates/alquiler_form.html
{% extends 'alta.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block formulario %}

<style>
  .two-columns {
    column-count: 2;
    column-gap: 20px; /* Espacio entre columnas */
}
</style>

<form  method="post">
  {% csrf_token %}
  {{ form.non_field_errors }}
  <br />
  <div class="row">
    <div class="col">
      <div class="form-group">
        {{ form.afiliado.label_tag }}
        {{ form.afiliado }}
        <small class="error-text" style="color: red;">{{ form.afiliado.error }}</small>
      </div>
    </div>
    
    <div class="col">
      <div class="form-group">
        {{ form.salon.label_tag }}
        {{ form.salon }}
        <small class="error-text" style="color: red;">{{ form.salon.error }}</small>
      </div>
    </div>
  </div> 
  
  <div class="row">
    <div class="col">
      <div class="form-group">
        {{ form.turno.label_tag }}
        {{ form.turno }}
        <small class="error-text" style="color: red;">{{ form.turno.error }}</small>
      </div>
    </div>
    
    <div class="col">
      <div class="form-group">
        {{ form.seguro.label_tag }}
        {{ form.seguro }}
        <small class="error-text" style="color: red;">{{ form.seguro.error }}</small>
      </div>
    </div>
    
    <div class="col">
      <div class="form-group">
        {{ form.fecha_alquiler.label_tag }}
        {{ form.fecha_alquiler }}
        <small class="error-text" style="color: red;">{{ form.fecha_alquiler.error }}</small>
      </div>
    </div>
  </div>

    <div class="row text-center">
      <div class="col">
        <button href="{% url 'alquiler:pagar_alquiler_crear' %}" class="btn btn-success">Pagar</button>
      </div>
    </div>
  </form>

  <script type="text/javascript" src="{% static 'Libs/js/jquery-1.11.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'Libs/js/jquery-iu.js' %}"></script>
<script type="text/javascript" src="{% static 'selectable/js/jquery.dj.selectable.js' %}"></script>
<link href="{% static 'selectable/css/dj.selectable.css' %}" type="text/css" media="all" rel="stylesheet">

{% endblock %}

sec2/apps/alquileres/templates/gestion_servicio.html
{% extends 'app_alquileres_alta_y_listado.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block alta %}
  <form method="post" action="{% url 'alquiler:gestion_servicio' %}">
    {% csrf_token %}
    <div class="row">
      <div class="col">
        <div class="form-group">
          <strong>{{ form.nombre.label_tag }}</strong>
          {{ form.nombre }}
        </div>
      </div>
    <div class="col align-self-center">
      <button type="submit" class="btn btn-success btn-sm">Crear</button>
    </div>
  </div>
  </form>
{% endblock %}

{% block listado %}

<table class="table table-sm table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Nombre</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for obj in object_list %}
    <tr class="bg-transition fila-personalizada">
        <td class="negrita"> {{ page_obj.start_index|add:forloop.counter0 }}</td>
        <td>{{ obj }}</td>

       <td class="text-end">
         <button type="button" class="btn btn-danger btn-sm btn-detalle" data-bs-toggle="modal" data-bs-target="#exampleModal_dar_de_baja_{{ obj.pk }}"><i class="fa-regular fa-circle-down"></i> Eliminar</button>
         {% include 'modal_confirm_baja_servicio.html' with object=obj %}            

          {% comment %} <a href="{% url 'alquiler:servicio_detalle' pk=obj.pk %}" class="btn btn-info btn-sm btn-detalle"><i class="fa-regular fa-eye"></i> Detalle</a> {% endcomment %}
          {% comment %} <a href="{% url 'alquiler:servicio_editar' obj.pk %}" class="btn btn-primary btn-sm btn-detalle"><i class="fa-regular fa-pen-to-square"></i> Modificar</a> {% endcomment %}
        </td>
      </tr>
    {% endfor %}
  </tbody>

</table>
{% endblock %}

sec2/apps/alquileres/templates/lista_alquileres.html
      <table class="table table-sm table-hover">
        <thead>
          <tr>
            <th>#</th>
            <th>Salon</th>
            <th>fecha_alquiler</th>
            <th>turno</th>
            <th>Afiliado</th>
            <th colspan="2">Precio</th>
          </tr>
        </thead>
    
        <tbody>
          {% for alquiler in alquileres %}
            <tr class="bg-transition fila-personalizada">
              <td class="negrita">{{ forloop.counter }}</td>
              <td>{{ alquiler.salon.nombre }}</td>
              <td>{{ alquiler.fecha_alquiler|date:"d F Y" }}</td>
              <td>{{ alquiler.turno }}</td>
              <td>{{ alquiler.afiliado.persona.dni }}</td>
              <td>${{ alquiler.salon.precio }}</td>
              <td class="text-end">
                <a href="{% url 'alquiler:alquiler_detalle' alquiler.pk %}" class="btn btn-sm btn-info btn-detalle"><i class="fa-regular fa-eye"></i> Detalle</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

sec2/apps/alquileres/templates/modal_confirm_baja_alquiler.html
<div class="modal fade" id="exampleModal_eliminar_alquiler" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">

  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Eliminar alquiler</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-center">¿Estás seguro de que deseas dar de baja al alquiler?</div>
      
      <div class="modal-footer">
        <a href="{% url 'alquiler:alquiler_eliminar' alquiler.pk %}" class="btn btn-danger">Eliminar</a>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

sec2/apps/alquileres/templates/salon_detalle.html
{% extends 'detalle_listado.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block detalle %}

<h3> Datos del Salon </h3>

<div class="row row-cols-2 row-cols-sm-4 row-cols-md-6">
  <div class="col">
    <p class="negrita">Salón: </p>
  </div>
  <div class="col">
    <p>{{ salon.nombre }}</p>
  </div>

  <div class="col">
    <p class="negrita">Localidad: </p>
  </div>
  <div class="col">
    <p>{{ salon.localidad }}</p>
  </div>

  <div class="col">
    <p class="negrita">Direccion: </p>
  </div>
  <div class="col">
    <p>{{ salon.direccion }}</p>
  </div>
</div>


<div class="row row-cols-2 row-cols-sm-4 row-cols-md-6">
  <div class="col">
    <p class="negrita">Capacidad: </p>
  </div>
  <div class="col">
    <p>{{ salon.capacidad }}</p>
  </div>

  <div class="col">
    <p class="negrita">Encargado: </p>
  </div>
  <div class="col">
    <p>{{ salon.encargado }}</p>
  </div>
</div>


<div class="row row-cols-2 row-cols-sm-4 row-cols-md-6">
    <div class="col">
      <p class="negrita"> Precio: </p>
    </div>
    <div class="col">
      <p>{{ salon.precio }}</p>
    </div>
  
    <div class="col">
      <p class="negrita">Tipo salon: </p>
    </div>
    <div class="col">
      <p>{{ salon.get_tipo_salon_display }}</p>
    </div>
    {% if salon.fechaBaja %}
    <div class="col">
      <p class="negrita">Fecha baja: </p>
    </div>
    <div class="col">
      <p>{{ salon.fechaBaja }}</p>
    </div>
    {% endif %}
  </div>
{% endblock %}

{% block botones %}

<div class="col">
  <a href="{% url 'alquiler:salon_listar' %}" class="btn btn-sm btn-secondary btn-detalle">
  <i class="fa-solid fa-arrow-left"></i> Ir al listado
  </a>
</div>

<div class="col">
  <a href="{% url 'alquiler:encargado_detalle' pk=salon.encargado.pk %}" class="btn btn-sm btn-info btn-detalle">
    <i class="fa-solid fa-person-shelter"></i> Ir al encargado
  </a>
</div>


{% if not salon.fechaBaja %}
<div class="col d-flex justify-content-end">
  <button type="button" class="btn btn-danger btn-sm btn-detalle" data-bs-toggle="modal" data-bs-target="#exampleModal_eliminar_salon"><i class="fa-regular fa-circle-down"></i> Dar de Baja</button>
  {% include 'modal_confirm_baja_salon.html' %}
</div>
{% endif %}

{% endblock %}


{% block listado_asociado %}
{% if salon.alquileres.all %}
<div class="container-sm">
    <h3 class="subtitulo">{{ tituloListado1 }}</h3>
    {% include "lista_alquileres.html" with alquileres=salon.alquileres.all %}
</div>
{% endif %}

{% endblock %}

{% block extrajs_intermedia %}
<script>
  var listaEsperaWindow = null;

  function openOrFocusWindow(url, name, width, height) {
    // Verifica si la ventana ya está abierta
    if (listaEsperaWindow && !listaEsperaWindow.closed) {
      // Si está abierta, enfócala
      listaEsperaWindow.focus();
    } else {
      // Si no está abierta, abre una nueva ventana
      listaEsperaWindow = window.open(url, name, 'width=' + width + ',height=' + height);
    }
  }
</script>
{% endblock %}