sec2/apps/cursos/urls.py
from django.urls import path
from .views.actividad_views import *
from .views.curso_views import *
from .views.dictado_views import *
from .views.horario_views import *
from .views.clase_views import *
from .views.profesor_views import *
from .views.alumno_views import *
from .views.aula_views import *
from .views.pago_views import *
from .views.views import *

app_name="cursos"

urlpatterns = [
    # PRINCIPAL
    path('',index, name="index"),

    # ACTIVIDADES
    path('actividades/', GestionActividadView.as_view(), name="gestion_actividad"),
    path('actividades/actividad/<int:pk>', ActividadDetailView.as_view(), name="actividad_detalle"),
    path('actividades/actividad/<int:pk>/editar', ActividadUpdateView.as_view(), name="actividad_editar"),
    path('actividades/actividad/<int:pk>/eliminar', actividad_eliminar, name="actividad_eliminar"),

    # AULAS
    path('aulas/', GestionAulaView.as_view(), name="gestion_aula"),
    path('aulas/aula/<int:pk>/', AulaDetailView.as_view(), name='aula_detalle'),
    path('aulas/aula/<int:pk>/editar', AulaUpdateView.as_view(), name="aula_editar"),
    path('aulas/<int:pk>/eliminar', aula_eliminar, name="aula_eliminar"),

    # PROFESOR
    path('profesores', ProfesorListView.as_view(), name="profesor_listado"),
    path('profesores/profesor/crear', ProfesorCreateView.as_view(), name="profesor_crear"),
    path('profesores/profesor/<int:pk>', ProfesorDetailView.as_view(), name="profesor_detalle"),
    path('profesores/profesor/<int:pk>/editar', ProfesorUpdateView.as_view(), name="profesor_editar"),
    path('profesores/profesor/<int:pk>/eliminar', profesor_eliminar, name="profesor_eliminar"),

    # CURSOS
    path('cursos/listado', CursoListView.as_view(), name="curso_listado"),
    path('cursos/curso/crear/', CursoCreateView.as_view(), name="curso_crear"),
    path('cursos/curso/<int:pk>', CursoDetailView.as_view(), name="curso_detalle"),
    path('cursos/curso/<int:pk>/editar', CursoUpdateView.as_view(), name="curso_editar"),
    path('cursos/curso/<int:pk>/eliminar', curso_eliminar, name="curso_eliminar"),
    path('cursos/curso/<int:pk>/listaespera', cursoListaEspera, name="curso_lista_espera"),
    path('cursos/curso/<int:pk>/listaespera/rol/<int:rol_pk>/<str:accion>/', gestionListaEspera, name="gestion_lista_espera"),
    
    # GESTION DE LISTA DE ESPERA
    path('cursos/curso/<int:pk>/listaespera/alumnopotencial/inscribir', AlumnoPotencialCreateView.as_view(), name="alumno_nuevo_lista_espera"),

    ## VERIFICAR Y BUSCAR PERSONA ANTES DE PROCEDER A LA INSCRIPCION
    path('cursos/curso/<int:curso_pk>/verificarpersona', VerificarInscripcionView.as_view(), name="verificar_persona"),
    path('buscar-persona/', BuscarPersonaView.as_view(), name='buscar_persona'),

    # DICTADOS (accedido desde cursos)
    path('cursos/curso/<int:pk>/dictados/dictado/crear', DictadoCreateView.as_view(), name="dictado_crear"),
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>', DictadoDetailView.as_view(), name="dictado_detalle"),
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/editar', DictadoUpdateView.as_view(), name="dictado_editar"),
    
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/finalizar', finalizarDictado , name="dictado_finalizar"),

    # HORARIO (accedido desde dictado)
    path('curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/horarios/horario/crear/', HorarioCreateView.as_view(), name='horario_crear'),
    path('curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/horarios/horario/<int:horario_pk>/elminar', eliminarHorario, name='horario_eliminar'),

    # ASIGNACIÓN DE AULA (accedido desde el horario)
    path('curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/horarios/horario/<int:horario_id>/vincularAula/', asignar_aula, name='asignar_aula'),

    # CLASE (accedido desde dictaod)
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_id>/generarclaeses/', generar_clases, name="generar_clases"),
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/clases/clase/<int:clase_pk>', ClaseDetailView.as_view(), name="clase_detalle"),
    
    # ALUMNO (accedido desde el dictado)

    #CONTROL DE ASISTENCIA
    path('marcar_asistencia/Alumno/<int:clase_id>/', marcar_asistencia, name='generar_asistencia'),

    #ALUMNNOS POR CURSO
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/Alumnos', AlumnosEnDictadoList.as_view(), name="alumno_inscripto"),

    # GESTION DE INSCRIPCION
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/<str:tipo>/<int:persona_pk>/Incripcion/<str:accion>/', gestionInscripcion, name="gestion_inscripcion"),
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/AlumnoNuevo/inscribir', AlumnoCreateView.as_view(), name="alumno_nuevo_inscribir"),

    path('alumnos', AlumnosListView.as_view(), name="alumnos_listado"),
    path('alumnos/alumnno/<int:pk>/', AlumnoDetailView.as_view(), name="alumno_detalle"),
    path('alumnos/alumno/<int:pk>/eliminar', alumno_eliminar, name="alumno_eliminar"),

    #GENERAR PDF
    path('generar-pdf-afiliado-dictado/<int:dictado_pk>/<int:persona_pk>', generarPDF_Afiliado , name="generar_pdf_dictado_finalizado_afiliado"),
    
    #NO SE UTILIZARIA
    path('cursos/curso/<int:curso_pk>/dictados/dictado/<int:dictado_pk>/Alumnos/listaEspera', listaEspera , name="dictado_lista_espera"),
    path('pago/listado/profesor', PagoProfesorListView.as_view() ,name="pago_cuota_profesor_listado"),
    path('pago/profesor/crear', PagoProfesorCreateView.as_view(), name="pago_profesor"),
    path('pago/profesor/<int:pk>', PagoProfesorDetailView.as_view(), name="pago_profesor_detalle"),
    path('get_dictados_por_titular/<int:titular_pk>/', get_dictados_por_titular, name='get_dictados_por_titular'),

    path('pago/listado/alumno', PagoAlumnoListView.as_view() ,name="pago_cuota_alumno_listado"),
    path('pago/obtenerDictadosEnCurso/<int:pk>', obtenerDictadosEnCurso ,name="obtenerDictadoEnCurso"),

    path('pago/alumno/crear', PagoAlumnoCreateView.as_view(), name="pago_alumno_crear"),
    path('pago/alumno/<int:pk>', PagoAlumnoDetailView.as_view(), name="pago_alumno_detalle"),

    path('get_dictados_por_alumno/<int:rol_pk>/', get_dictados_por_alumno, name='get_dictados_por_alumno'),
]

sec2/sec2/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


handler403 = custom_403_view
urlpatterns = [
    
    #PRINCIPALES
    
    path('', home, name="login"),
    path('admin/', admin.site.urls),
    path('home/', home, name="home"),

    #APLICACIONES
    path('home/app_afiliados/',include('apps.afiliados.urls')),
    path('home/app_cursos/',include('apps.cursos.urls')),
    path('home/app_personas/',include('apps.personas.urls')),
    path('home/app_alquileres/',include('apps.alquileres.urls')),
    path('home/app_reportes/',include('apps.reportes.urls')),

    path('',include('apps.users.urls')),
    path('select2/', include('django_select2.urls')),
    path('selectable/', include('selectable.urls')),

    path('manual_usuario/', abrirManualUsuario, name="manual_usuario"),
    path('documentacion_tecnica/', abrirDocumentacionTecnica, name="documentacion_tecnica"),


]

sec2/apps/cursos/models.py
from django.db import models
from django.http import Http404, HttpResponse
from apps.personas.models import Rol
from utils.constants import *
from utils.choices import *
from utils.funciones import registrar_fuentes, validate_no_mayor_actual
from utils.regularexpressions import *
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import date

# ------------- ACTIVIDAD --------------------
class Actividad(models.Model):
    nombre = models.CharField(
        max_length=50,
        validators=[text_validator],  # Añade tu validador personalizado si es necesario
        help_text="Solo se permiten letras y espacios."
    )
    
    def __str__(self):
        return f"{self.nombre}"

# ------------- AULA --------------------
class Aula(models.Model):
    tipo = models.CharField(max_length=50, choices=TIPO_AULA, help_text="Tipo de aula")
    numero = models.PositiveIntegerField(help_text="Numero de aula")
    capacidad = models.PositiveIntegerField(help_text="Capacidad máxima")

    def clean(self):
        if self.numero <= 0:
            raise ValidationError({'numero': 'El número de aula debe ser mayor que 0.'})
        if self.capacidad <= 0:
            raise ValidationError({'cupo': 'La capacidad máxima del aula debe ser mayor que 0.'})

    def __str__(self):
        if self.tipo == 'normal':
            return 'Aula {}'.format(self.numero)
        return 'Computación {}'.format(self.numero)

#------------- LISTA DE ESPERA --------------------
class ListaEspera(models.Model):
    curso = models.ForeignKey('Curso', on_delete=models.CASCADE, related_name='inscritos_lista_espera')
    rol = models.ForeignKey(Rol, on_delete=models.CASCADE)
    fechaInscripcion = models.DateTimeField(auto_now_add=True)
    
#------------- CURSO --------------------
class Curso(models.Model):
    class Meta:
        permissions = [("permission_gestion_curso", "Control total curso")]

    # ForeignKey
    actividad = models.ForeignKey(Actividad, on_delete=models.SET_NULL, blank=True, null=True)
    lista_espera = models.ManyToManyField(ListaEspera, blank=True, related_name='cursos_en_lista_espera')  # Change the related_name here

    area = models.PositiveSmallIntegerField(choices=AREAS, blank=True, null=True)
    requiere_certificado_medico = models.BooleanField(default=False)
    requiere_equipamiento_informatico = models.BooleanField(default=False)
    es_convenio = models.BooleanField(default=False)
    modulos_totales= models.PositiveIntegerField(help_text="Horas totales del curso")    
    nombre = models.CharField(
        max_length=50,
        validators=[text_and_numeric_validator],
        help_text="Solo se permiten letras, números y espacios, con o sin tildes."
    )
    descripcion = models.CharField(
        max_length=255,
        validators=[text_and_numeric_validator],  # Añade tu validador personalizado si es necesario
        help_text="Descripción del curso"
    )
    cupo_estimativo = models.PositiveIntegerField(
        help_text="Maximo por dictado",
        validators=[
            MinValueValidator(1, message="Valor mínimo permitido es 1."),
            MaxValueValidator(100, message="Valor máximo es 100."),
        ],
        null=True,
    )
    precio_total = models.DecimalField(
        help_text="Costo total del curso (Alumno)",
        max_digits=10,
        decimal_places=0,
        blank=True,   # Set this to True to make the field optional
        null=True,    # Also set null to True if you want to allow NULL values in the database
        default=0     # Set the default value to 0
    )
    precio_estimativo_profesor = models.DecimalField(
        help_text="Precio a pagar por profesor (estimado)",
        max_digits=10,
        decimal_places=0,
        blank=True,   # Set this to True to make the field optional
        null=True,    # Also set null to True if you want to allow NULL values in the database
        default=0     # Set the default value to 0
    )
    
    fechaBaja= models.DateField(
        null=True,
        blank=False,
    )

    
    def __str__(self):
        return f"{self.nombre}"
    
    def get_tipo_curso(self):
        if self.es_convenio:
            return 'convenio'
        elif self.requiere_certificado_medico:
            return 'actividad'
        else:
            return 'sec'

#------------- DICTADO --------------------
from django.utils.crypto import get_random_string

class Dictado(models.Model):
    # ForeignKey
    curso = models.ForeignKey(Curso, related_name="dictado_set", on_delete=models.CASCADE, null=True, blank=True)
    legajo = models.CharField(max_length=4, null=True, default=get_random_string(length=4, allowed_chars='1234567890'))
    modulos_por_clase= models.PositiveIntegerField(help_text="Horas por clase")
    asistencia_obligatoria = models.BooleanField(default=False)
    periodo_pago=models.PositiveSmallIntegerField(choices=PERIODO_PAGO)
    estado = models.PositiveSmallIntegerField(choices=ESTADO_DICTADO, default=1)
    fecha = models.DateTimeField(help_text="Seleccione la fecha de inicio")
    fecha_fin = models.DateTimeField(null=True,blank=True )
    cupo_real = models.PositiveIntegerField(
        help_text="Máximo inscriptos",
        validators=[
            MinValueValidator(1, message="Valor mínimo permitido es 1."),
            MaxValueValidator(100, message="Valor máximo es 100."),
        ]
    )
    descuento = models.PositiveIntegerField(
        help_text="Exclusivo para afiliados",
        validators=[
            MinValueValidator(0, message="El descuento no puede ser menor que 0."),
            MaxValueValidator(100, message="El descuento no puede ser mayor que 100."),
        ]
    )
    precio_real_profesor = models.DecimalField(
        help_text="Precio a pagar por profesor (real)",
        max_digits=10,
        decimal_places=0,
        blank=True,   # Set this to True to make the field optional
        null=True,    # Also set null to True if you want to allow NULL values in the database
        default=0     # Set the default value to 0
    )

#------------- HORARIO --------------------
from datetime import datetime, timedelta

class Horario(models.Model):
    # ForeignKey
    dictado = models.ForeignKey(Dictado, related_name="horarios", null=True, on_delete=models.CASCADE)
    
    dia_semana = models.PositiveSmallIntegerField(choices=DIAS_SEMANA_CHOICES)
    hora_inicio = models.TimeField(help_text="Ingrese la hora en formato de 24 horas (HH:MM)")
    hora_fin = models.TimeField(blank=True, null=True)
    #Utilizado para controlar que no se creen horarios antes del primer dictado creado
    es_primer_horario = models.BooleanField(default=False)  # Campo booleano con valor por defecto False

    def clean(self):
        if self.hora_inicio and self.dictado and self.dictado.modulos_por_clase:
            # Calcular la hora de fin al limpiar los datos del modelo
            hora_inicio_datetime = datetime.combine(datetime.today(), self.hora_inicio)
            tiempo_modulo = timedelta(hours=self.dictado.modulos_por_clase)
            hora_fin_datetime = hora_inicio_datetime + tiempo_modulo
            self.hora_fin = hora_fin_datetime.time()

    def calcular_hora_fin(self, hora_inicio, modulos_por_clase):
        # Calcular la hora de fin en cualquier otro lugar si es necesario
        if hora_inicio and modulos_por_clase:
            hora_inicio_datetime = datetime.combine(datetime.today(), hora_inicio)
            tiempo_modulo = timedelta(hours=modulos_por_clase)
            hora_fin_datetime = hora_inicio_datetime + tiempo_modulo
            return hora_fin_datetime.time()

# ------------- RESERVA --------------------
class Reserva(models.Model):
    # ForeignKey
    horario = models.ForeignKey(Horario, related_name="reservass", on_delete=models.CASCADE, null=True, blank=True)
    aula = models.ForeignKey(Aula, related_name="reservas", on_delete=models.CASCADE, null=True, blank=True)
    fecha = models.DateField()

#------------- ALUMNO --------------------
class Alumno(Rol):
    # ForeignKey
    dictados = models.ManyToManyField(Dictado, related_name="alumnos", blank=True)
    # lista_espera = models.ManyToManyField('Dictado', related_name='alumnos_en_espera', blank=True)
    
    # Si realmente es un alumno o solo un interesado en algun curso
    es_potencial = models.BooleanField(default=True) 

    TIPO = ROL_TIPO_ALUMNO
    def agregar_dictado(self, dictado):
        if dictado.cupo > dictado.alumnos.count():
            self.dictados.add(dictado)
            return True
        else:
            # self.lista_espera.add(dictado)
            return False
    
    def esta_inscripto_o_en_espera(self, dictado):
        return dictado in self.dictados.all() 
    # or dictado in self.lista_espera.all()

    def esta_inscrito_en_dictado(self, dictado_pk):
        """
        Verifica si el alumno está inscrito en el dictado con la clave primaria dictado_pk.
        Devuelve True si está inscrito, False en caso contrario.
        """
        return self.dictados.filter(pk=dictado_pk).exists()

    def darDeBaja(self):
        self.hasta = date.today()
        self.persona.save()
        self.save()

Rol.register(Alumno)

#------------- PROFESOR --------------------
class Profesor(Rol):
    # ForeignKey
    dictados = models.ManyToManyField(Dictado, through = "Titular", related_name="profesores", blank=True)
    TIPO = ROL_TIPO_PROFESOR
    actividades = models.ManyToManyField(Actividad, blank=True)
    dictados_inscriptos = models.ManyToManyField(Dictado, related_name="profesores_dictados_inscriptos", blank=True)
    # lista_espera = models.ManyToManyField(Dictado, related_name='profesores_en_espera', blank=True)

    ejerce_desde= models.DateField(
        null=True,
        blank=False,
        validators=[validate_no_mayor_actual]
    )
    
    def esRolActivo(self):
        rol = get_object_or_404(Rol, persona__pk=self.persona.pk)
        if rol.hasta:

sec2/apps/cursos/views/pago_views.py
# from ..models import Pago_alumno
# from ..forms.pago_alumno_forms import *
# from django.views.generic.edit import CreateView
# from django.urls import reverse_lazy

# class PagoAlumnoCreateView(CreateView):
#     model = Pago_alumno
#     form_class = FormularioPagoAlumno
#     template_name = 'otro/pago_alumno_form.html'  
#     success_url = reverse_lazy('cursos:cursos')
    
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['titulo'] = "Listado de profesores"
#         return context

sec2/apps/cursos/templates/dictado/dictado_detail.html
{% extends 'detalle_listado_app_cursos.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block detalle %}
<div class="row">

  <div class="col-md-2">
    <p class="negrita">Desc. afiliados:</p>
  </div>
  <div class="col-md-3">
    <p>{{ dictado.descuento }}% de descuento</p>
  </div>
  <div class="col-md-2">
    <p class="negrita">Titular:</p>
  </div>
  <div class="col-md-3">
    <p>{{ nombre_profesor }}</p>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    <p class="negrita">Valor:</p>
  </div>
  <div class="col-md-3">
    <p>{{costo_parcial}}</p> 
  </div>
  <div class="col-md-2">
    <p class="negrita">Módulos por Clase:</p>
  </div>
  <div class="col-md-4">
    <p>
      {% if dictado.modulos_por_clase == 1 %}
      {{ dictado.modulos_por_clase }} módulo ({{ dictado.modulos_por_clase }} hora por clase)
      {% else %}
      {{ dictado.modulos_por_clase }} módulos ({{ dictado.modulos_por_clase }} horas por clase)
      {% endif %}
    </p>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    <p class="negrita">Total de cupos:</p>
  </div>
  <div class="col-md-3">
    <p>{{ total_inscritos }}/{{ dictado.cupo_real }} participantes</p>
  </div>
  <div class="col-md-2">
    <p class="negrita">Fecha de inicio:</p>
  </div>
  <div class="col-md-2">
    <p>{{ dictado.fecha|date:"d \d\e F \d\e Y" }} </p>
  </div>
</div>


<div class="row">
  <div class="col-md-2">
    <p class="negrita">Estado:</p>
  </div>
  <div class="col-md-3">
    <p>{{dictado.get_estado_display}}</p>
  </div>
  <div class="col-md-2">
    <p class="negrita">Legajo:</p>
  </div>
  <div class="col-md-3">
    <p>{{dictado.legajo}}</p>
  </div>
</div>

  {% if dictado.fecha_fin %}
  <div class="row">
    <div class="col-md-2">
      <p class="negrita">Fecha de finalizacion:</p>
    </div>
    <div class="col-md-4">
      <p>{{ dictado.fecha_fin|date:"d \d\e F \d\e Y" }}</p>
    </div>
  </div>
  {% endif %}


<div class="row">
  <div class="col-md-2">
    <p class="negrita">Precio del profesor:</p>
  </div>
  <div class="col-md-3">
    <p>${{dictado.precio_real_profesor}}</p>
  </div>
</div>
{% endblock %}

{% block horarios %}
<div class="d-flex justify-content-center">
  {% include "dictado/modal_horario_dictado.html" %}
</div>
{% endblock %}

{% block botones %}
<div class="col">
  <a href="{% url 'cursos:curso_detalle' pk=dictado.curso.pk %}" class="btn btn-sm btn-secondary btn-detalle">
    <i class="fa-solid fa-arrow-left"></i> Volver al curso
  </a>
</div>

<div class="col"> 
  {% if not dictado.curso.fechaBaja %}
  <a href="{% url 'cursos:curso_lista_espera' curso.pk %}" 
    class="btn btn-warning btn-sm btn-detalle" 
    onclick="openOrFocusWindow(this.href, 'Lista de espera', 700, 400); return false;">
    <i class="fa-solid fa-list"></i>
    Lista de espera
  </a>
  {% endif %}
</div>

<div class="col">
    <button type="button" class="btn btn-info btn-sm btn-detalle" data-bs-toggle="modal" data-bs-target="#exampleModal">
      <i class="fa-solid fa-list"></i>
      Alumnos
    </button>
    {% include "dictado/modal_alumnos_dictado.html" %}
</div>
  
<div class="col">
    {% if not  hay_reserva %}
      <a href="{% url 'cursos:horario_crear' curso_pk=dictado.curso.pk dictado_pk=dictado.pk %}" class="btn btn-sm btn-outline-success btn-detalle">
        <i class="fa-regular fa-clock"></i> Nuevo Horario
      </a>

      {% elif todos_los_horarios_con_aula %}
      {% if not clases %}
      {% comment %} <a id="generar-clases-btn" href="{% url 'cursos:generar_clases' curso_pk=curso.pk dictado_id=dictado.pk %}" class="btn btn-outline-success btn-detalle"> {% endcomment %}
        <button id="generar-clases-btn" class="btn btn-outline-success btn-detalle" onclick="generarClases()">
          <i class="fa-solid fa-plus"></i> Generar clases
        </button>
        
        <script>
        function generarClases() {
          // Cambiar el contenido del botón al hacer clic en él
          var btn = document.getElementById('generar-clases-btn');
          btn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Generando clases...';
        
          // Deshabilitar el botón después de hacer clic para evitar múltiples clics
          btn.setAttribute('disabled', 'disabled');
        
          // Redirigir a la URL deseada
          window.location.href = "{% url 'cursos:generar_clases' curso_pk=curso.pk dictado_id=dictado.pk %}";
        }
        </script>


      {% elif dictado.estado == 2 %}
      <a href="{% url 'cursos:dictado_finalizar' curso_pk=curso.pk dictado_pk=dictado.pk %}" class="btn btn-sm btn-outline-danger btn-detalle">
        <i class="fa-solid fa-plus"></i> Finalizar
      </a>
      {% endif %}
    {% endif %}
  </div>
{% endblock %}

{% block listado_asociado %}

  {% if clases %}

  <div class="container-sm">
    <h3 class="subtitulo">{{ tituloListado }}</h3>
    <table class="table table-sm table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Fecha</th>
          <th class="text-center">Asistencia</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for clase in clases %}
          <tr>
            <td class="negrita"> {{ clases.start_index|add:forloop.counter0 }}</td>
            <td>{{ clase.reserva.horario.get_dia_semana_display }} {{ clase.reserva.fecha }}</td>
            <td class="text-center">  
              {% if clase.asistencia_tomada %}
              <i class="fa-solid fa-check" style="color:green"></i>
              {% else %}
              <i class="fa-solid fa-circle-exclamation" style="color: #FF8000;"></i>
              {% endif %}
            </td>
            {% comment %} <a href="{% url 'cursos:clase_detalle' curso_pk = curso.pk dictado_pk = dictado.pk clase_pk = clase.pk %}" class="btn btn-primary btn-detalle"><i class="fa-regular fa-eye"></i> Detalle</a> {% endcomment %}
            <td class="text-end">
              <a href="{% url 'cursos:clase_detalle' curso_pk=curso.pk dictado_pk=dictado.pk clase_pk=clase.pk %}" class="btn btn-info btn-detalle btn-sm"><i class="fa-regular fa-eye"></i> Detalle</a>
              {% comment %} <a href="{% url 'cursos:clase_detalle' curso_pk = curso.pk dictado_pk = dictado.pk clase_pk = clase.pk %}" class="btn btn-primary btn-detalle"><i class="fa-regular fa-eye"></i> Detalle</a> {% endcomment %}
            </td>
          </tr>
          
        {% endfor %}
      </tbody>
    </table>
    {% include 'pagination.html' with page_obj=clases %}

  {% endif %}
  </div>

  <script>
//------------------- GESTION DE INSCRIPCION --------------------
function gestionInscripcion(accion, curso_pk, dictado_pk, persona_pk, tipo) {
  var url = `{% url 'cursos:gestion_inscripcion' curso_pk=9999 dictado_pk=9999 persona_pk=8888 tipo='placeholder' accion='placeholder' %}`
    .replace('9999', curso_pk)
    .replace('9999', dictado_pk)
    .replace('8888', persona_pk)
    .replace('placeholder', tipo)  // Reemplazar el tipo dinámicamente
    .replace('placeholder', accion);  // Reemplazar la acción dinámicamente
  window.location.href = url;
}
// Llamadas específicas
function gestionInscripcionAfiliado(accion, curso_pk, dictado_pk, persona_pk) {
  gestionInscripcion(accion, curso_pk, dictado_pk, persona_pk, 'Afiliado');
}

function gestionInscripcionFamiliar(accion, curso_pk, dictado_pk, persona_pk) {
  gestionInscripcion(accion, curso_pk, dictado_pk, persona_pk, 'Familiar');
}

function gestionInscripcionProfesor(accion, curso_pk, dictado_pk, persona_pk) {
  gestionInscripcion(accion, curso_pk, dictado_pk, persona_pk, 'Profesor');
}

function gestionInscripcionAlumno(accion, curso_pk, dictado_pk, persona_pk) {
  gestionInscripcion(accion, curso_pk, dictado_pk, persona_pk, 'Alumno');
}
  </script>

    
  <script>
    var listaEsperaWindow = null;
  
    function openOrFocusWindow(url, name, width, height) {
      // Verifica si la ventana ya está abierta
      if (listaEsperaWindow && !listaEsperaWindow.closed) {
        // Si está abierta, enfócala
        listaEsperaWindow.focus();
      } else {
        // Si no está abierta, abre una nueva ventana
        listaEsperaWindow = window.open(url, name, 'width=' + width + ',height=' + height);
      }
    }
  </script>
  

  {% endblock %}

  

sec2/apps/cursos/templates/dictado/falta_profesor.html
{% extends 'home_curso.html' %}

{% block dinamica %}
  <h2 class="titulo">{{ titulo }}</h2>
  <p>Falta crear profesor antes de agregar un dictado.</p>
  
{% endblock %}